### ISSUE TITLE
Handle printing of exceptions better in python scripts

### ISSUE THREAD

**Issue by jsturdy** [cms-gem-daq-project/cmsgemos#102]
Some exceptions result in a failure to print causing the python tool to crash.  This behaviour needs to be fixed
 * ```An exception occurred cannot concatenate 'str' and 'exception' objects```

**Comment by jsturdy** [comment]
To add to this, for some failures in communication, it will be nice to catch some exception and gracefully exit, rather than resulting in ending the function call completely
* partial results from scan modules for example

**Comment by mexanick** [comment]
Very vague, most probably obsolete. Closing
