### ISSUE TITLE
read/write register list using the multiple transactions per dispatch

### ISSUE THREAD

**Issue by jsturdy** [cms-gem-daq-project/cmsgemos#113]
Currently seeing an error of the following sort when sending multiple (some number, not all) ```uhal``` transactions per ```dispatch``` call.
```
16-06-17 17:06:29.992061 [7fadb4dfa700] ERROR - Wrong Protocol Version! 0 != 2
16-06-17 17:06:29.992116 [7fadb4dfa700] ERROR - Unable to parse reply header 0x00000000 from URI "ipbustcp-2.0://192.168.2.42:60002", 41 bytes into IPbus reply payload.
16-06-17 17:06:29.992133 [7fadb4dfa700] ERROR - Original sent header was 0x2498011F, for base address 0x0040A029, 121 bytes into IPbus send payload
```

* Need to understand where the error is coming from (```CTP7``` or ```uhal```)
* Find if there is an undocumented behaviour of this functionality where only a specific number of transactions can be bundled, and this has to be done manually, rather than being taken care of by ```uhal```/```controlhub```

**Comment by mexanick** [comment]
Am I right that you observe this error only for certain multiple uhal transactions per dispatch?
If so, can you give two examples: successful dispatch and erroneous one?
Also couple of other questions:
do you observe errors always for the same calls, or they are floating?
how many transactions are bundled when you have error?

**Comment by jsturdy** [comment]
I only recently started investigating this and was able to get rid of the failures if I played around with how many transactions would work.
I've tried to start investigating further (replacing the OH broadcast with a multiple dispatch, etc), so I haven't  got the full picture of when/how this occurs yet, but I'm starting to expand my test suite :smile:
