### ISSUE TITLE
Feature Request: Latency Scan Step Size From Command Line 

### ISSUE THREAD

**Issue by bdorney** [cms-gem-daq-project/cmsgemos#115]
Looking at:

[GE11COSMICS@cosmicstandtif 20170616]$ /home/GE11COSMICS/Software/DAQ/vfatqc-python-scripts/ultraLatency.py -h
Usage: ultraLatency.py [options]

Options:
  -h, --help            show this help message and exit
  -s slot, --slot=slot  slot in uTCA crate
  -g gtx, --gtx=gtx     GTX on the AMC
  --shelf=shelf         uTCA shelf to access
  -d, --debug           print extra debugging information
  -r, --reset           reset link error counters
  --errors=errorRate    calculate link error rates for N seconds
  --testbeam            fixed IP address for testbeam
  --namc=namc           Number of register tests to perform on the amc
                        (default is 100)
  --noh=noh             Number of register tests to perform on the OptoHybrid
                        (default is 100)
  --ni2c=ni2c           Number of I2C tests to perform on the VFAT2s (default
                        is 100)
  --ntrk=ntrk           Number of tracking data packets to readout (default is
                        1000)
  --writeout            Write the data to disk when testing the rate
  --tests=tests         Tests to run, default is all
  --doLatency           [OPTIONAL] Run latency scan to determine the latency
                        value
  --QC3test             [OPTIONAL] Run a shortened test after covers have been
                        applied
  --ztrim=ztrim         Specify the p value of the trim
  --scanmin=scanmin     Minimum value of scan parameter
  --scanmax=scanmax     Maximum value of scan parameter
  --nevts=nevts         Number of events to count at each scan point
  --vt1=vt1             VThreshold1 DAC value for all VFATs
  --vt2=vt2             Specify VT2 to use
  --mspl=MSPL           Specify MSPL.  Must be in the range 1-8 (default is 4)
  --filename=filename   Specify Output Filename
  --internal            Run a latency scan using the internal calibration
                        pulse

There is no option to supply the step size of the latency scan from command line.  Request feature implementation for an option like --stepSize which would go from --scanmin to --scanmax at the supplied step size.

**Comment by jsturdy** [comment]
Moved to cms-gem-daq-project/vfatqc-python-scripts#88
