### ISSUE TITLE
Go to error when output file can not be created or written

### ISSUE THREAD

**Issue by jsturdy** [cms-gem-daq-project/cmsgemos#116]
Realized that there doesn't seem to be any upwards notification from the readout application to the supervisor (or even into the FSM of the readout application) if the desired output file can't be written.
This should cause the readout application's FSM to go to error

**Comment by mexanick** [comment]
Has this been ever fixed?

**Comment by cgalloni** [comment]
@jsturdy, do you remember if this was fixed?

**Comment by jsturdy** [comment]
Unlikely, I doubt that the `try/catch` that exists would catch this type of error

**Comment by cgalloni** [comment]
Moved to GitLab [issue](https://gitlab.cern.ch/cmsgemonline/cmsgemos/-/issues/94) for implementation.
