### ISSUE TITLE
Exception in amc_info_uhal.py if --short option not used at cmd line

### ISSUE THREAD

**Issue by bdorney** [cms-gem-daq-project/cmsgemos#118]
When calling:

amc_info_uhal.py -s2 -g0 --shelf=3 --short 2>&1 | tee amc_info.txt

Expected behavior is obtained (see [amc_info.txt](https://github.com/cms-gem-daq-project/cmsgemos/files/1088096/amc_info.txt))

When calling:

amc_info_uhal.py -s2 -g0 --shelf=3 2>&1 | tee amc_info_withException.txt

e.g. missing the --short argument an exception is thrown as shown in [amc_info_withException.txt](https://github.com/cms-gem-daq-project/cmsgemos/files/1088097/amc_info_withException.txt)

**Comment by bdorney** [comment]
Indeed, however @jsturdy requested an issue so it could be tracked.

**Comment by jsturdy** [comment]
Changes in the generated uhal address table removed a register block that was previously used.
Have to understand whether to modify [evka85/GEM_AMC](https://github.com/evka85/GEM_AMC/blob/master/scripts/generate_registers.py) to update how the address table is generated, or whether modification of the code here is the better long-term solution
