### ISSUE TITLE
Exception in amc_info_uhal.py if -r option used at cmd line

### ISSUE THREAD

**Issue by bdorney** [cms-gem-daq-project/cmsgemos#119]
Based on feedback from DAQ expert tried to issue a reset command to the CTP7 with command line option -r.

Generated the exception shown: [amc_info_resetExcept.txt](https://github.com/cms-gem-daq-project/cmsgemos/files/1089047/amc_info_resetExcept.txt)

**Comment by jsturdy** [comment]
Needs an update to the reset function call, as it's using the old address table

**Comment by bdorney** [comment]
closing as stale
