### ISSUE TITLE
Latency scan monitoring

### ISSUE THREAD

**Issue by mexanick** [cms-gem-daq-project/cmsgemos#127]
## Brief summary of issue
Latency scan doesn't provide any monitoring capabilities to see how the scan is progressing

### Types of issue

- [ ] Feature request: add certain monitoring printouts to the log file

## Context (for feature requests)

I'm going to add following information:
- OH CRC counters for each VFAT at the beginning of the scan and after it finishes- this might affect the number of triggers we take since the data with failed CRC may be discarded. _QUESTION_: do we want to add this printout (24 values per chamber) for all the scans or only for Latency?
- Number of L1As reported by AMC13, CTP7 and OH (each 1000 L1As send from AMC13) -- _only for Latency scan_

Do I miss anything? Any other suggestions?

**Comment by cbravo135** [comment]
Does a CRC error counter for each VFAT already exist or is it just one which is a sum over all VFATs?

**Comment by cbravo135** [comment]
I also think we should add a printout of the OH CRC counters to optohybrid_info_uhal.py in cmsgemos.

**Comment by mexanick** [comment]
These are per-VFAT counters. Also they could be reset individually at the beginning of the run

**Comment by cbravo135** [comment]
Yes, lets reset them at the beginning of the scan and read them into a printout at the end.

**Comment by jsturdy** [comment]
Regarding the question 
> Do we want to add this printout (24 values per chamber) for all the scans or only for Latency:

it would only make sense for a scan that is using the tracking data, as that's the only case where it would directly tell us anything
* Now that I understand your request better, the next question is how often do you really want this progress information to be logged?
  * Do you really want it to be fixed to be per/1000? I'd say that as a start it could be once per N triggers requested per point
* Still better would be adding a progress counter to the firmware module itself, that can be read from the status register, reporting the current scan value.
  * This could be added to the additional register I mention below as there would be 8 bits free anyway
* What is the purpose for adding CRC printing?
  * If it's what I think (debugging issues we've been seeing), then I would add it in the firmware and put it in the status register (24 bits in a new status register) with a 1 signifying that a given VFAT had a CRC error during the scan
  * Starting the scan automatically resets this to 0
  * The status register currently has 24 bits which are used to report which VFATs have data that are available for readout.  This is not (at the moment) directly used and could be repurposed for this new status bit, but better would be to add another register for this additional status check.
  * It would not preclude from printing out the CRC error counts, but would be a nice succinct way to summarize the information that I think @mexanick is hoping to add.

**Comment by mexanick** [comment]
@jsturdy , thanks for the comments! While I certainly agree with your proposal to put things in the FW, it make take some time. I propose we add it now in SW and later migrate to FW. I'll make a pilot pull request later today so we can review

**Comment by mexanick** [comment]
OK guys, I've tested the improvements at QC8, added couple of debug commits - it works now. Please review again. The output is like I expect, however there's one open question remaining: I followed @jsturdy suggestion to have updates every n_triggers, but for example one of the latest latency scan setups at QC8 had 5000 triggers per point, so the update will be really rare... I can change the code to provide either n_triggers or n_seconds update. Do we want to go for it?

**Comment by cbravo135** [comment]
I also just learned from Thomas that there is a CRC Good counter in addition to the CRC Bad counter. We should also be looking at this counter and make sure CRC Good + CRC Bad makes sense.

**Comment by mexanick** [comment]
We can do this eventually, but let's wait Jared's feedback

**Comment by cbravo135** [comment]
I think it makes sense for this to be included in this PR.

**Comment by bdorney** [comment]
@mexanick, regarding updates every n_triggers.  Can we make this a command line argument with a default value that is suitable for P5?  Then we can change it for the cosmic stand whenever needed.

 Then Additional comment, based on terminal output shown: http://cmsonline.cern.ch/cms-elog/996605

I would suggest to reset the AMC and OH0 L1A counters whenever the scan is started so that they match with the AMC13 L1A as the scan progresses.  Explicitly:

`AMC13: 3
AMC: 481441
OH0: 669111709`

It would be easier for the user if these numbers matched (in addition to showing the different) and could help troubleshooting during the scan.

**Comment by mexanick** [comment]
Cross-posting from mattermost for the records:

* AMC13 triggers are resetted at the beginning of the scan, but this is valid ONLY for local amc13 triggering or LEMO, when taking data with TTC stream this won't happen
* The L1A counts will be identical only if the trigger rate is low because there's some time interval between readouts
    * 100kHz LHC triggers will result in 10uS time interval between triggers which will lead to different readings

Because of the above reasons I doubt that it is useful to reset all counters. On the other hand, to avoid confusion, I can remove the first printout because the one which matters is happening at the end, where the difference (i.e. number of processed L1As) is shown. Those numbers can also be slightly different, but should be very close to each other
