### ISSUE TITLE
Feature Request: paths.sh checks status of uhal links

### ISSUE THREAD

**Issue by bdorney** [cms-gem-daq-project/cmsgemos#130]
## Brief summary of issue
When performing a SW update via git the uhal links in:

`$BUILD_HOME/cmsgemos/setup/etc/addresstables`

Are broken and a call of:

`$BUILD_HOME/cmsgemos/setup/etc/addresstables/linkuhaltables.sh`

Is required to restore the links.

### Types of issue

- [ ] Bug report (report an issue with the code)
- [X] Feature request (request for change which adds functionality)

## Expected Behavior

Add a block of code in:

`$BUILD_HOME/cmsgemos/setup/paths.sh`

That would check if the links exist and are not broken.  If they are found to be broken paths.sh should call linkuhaltables.sh

Something like: 
```bash
# Link connections & address tables
echo "Checking Links"
cd $BUILD_HOME/cmsgemos/setup/etc/addresstables
ln -sf connections_tif.xml connections.xml
if [ -L uhal_gem_amc_ctp7_amc.xml ]; then
    if readlink -q uhal_gem_amc_ctp7_amc.xml >/dev/null ; then
        echo "Links no good, re-making"
        ./linkuhaltables.sh $FIRMWARE_GEM/CTP7/address_table_v1_9_4 v1_9_4_GBT .
    else
        echo "Links Checkout"
    fi
fi
```
Don't know how to make indentations work, the above suggestion might need some tweaking.

## Current Behavior

A call of:  `$BUILD_HOME/cmsgemos/setup/etc/addresstables/linkuhaltables.sh`
 Is required after every software update.  This leads to the possibility that the person performing the update forgets to call the script as reported:  http://cmsonline.cern.ch/cms-elog/997946

## Context (for feature requests)
 DAQ Expert making SW update forgets to call:  
`$BUILD_HOME/cmsgemos/setup/etc/addresstables/linkuhaltables.sh`
 Leads to downtime of the system.

@lmoureaux

**Comment by jsturdy** [comment]
* Can agree to an update that will check and report a message to the user, telling the user to set up the links themselves
* Will be unnecessary soon for production systems, which will have all necessary things set up by the rpm, removing dependence on:
  * setting links
  * sourcing env (well, it will depend on how the system is set up)
  * setting up `XDAQ_DOCUMENT_ROOT` differently

**Comment by bdorney** [comment]
`paths.sh` no longer used, closing as irrelevant.
