### ISSUE TITLE
xdaq data taking for the cosmicstand fails

### ISSUE THREAD

**Issue by nvanegas** [cms-gem-daq-project/cmsgemos#131]
## Brief summary of issue

@jsturdy  and 
@bdorney 

running  an xdaq on the cosmic stand we ran into different problems. The elog is is 

[http://cmsonline.cern.ch/cms-elog/998313](http://cmsonline.cern.ch/cms-elog/998313)

with three different logfiles, one for every time the scan was launched. They are

/home/GE11COSMICS/Software/DAQ/cmsgemos/xdaq_log_RunType_20170719.txt
/home/GE11COSMICS/Software/DAQ/cmsgemos/xdaq_log_RunType_20170719-2nd.txt
/home/GE11COSMICS/Software/DAQ/cmsgemos/xdaq_log_RunType_20170719-3th.txt

The log files contain the warnings and error messages received as well as the commands used to launch.

### Types of issue

- [x ] Bug report (report an issue with the code)
- [ ] Feature request (request for change which adds functionality)

**Comment by bdorney** [comment]
Looks like this particular issue was due to not recompiling the code after an update which lead to the xml not being understood.

This issue can be closed.
