### ISSUE TITLE
Local DB update problem

### ISSUE THREAD

**Issue by mexanick** [cms-gem-daq-project/cmsgemos#132]
## Python logging  interface has been updated, however this update didn't propagate to all (sub)packages. Also it's logger usage is different in different python scripts.
Also wrong python version is used during compilation (system-wide python 2.6 instead of python 2.7)

### Types of issue

- [ x ] Bug report (report an issue with the code)
- [ ] Feature request (request for change which adds functionality)

## Expected Behavior

Correct DB update

## Current Behavior

Query module intended to update the local DB is not working correctly with the logger. 
Due to wrong version of python involved in compilation of gemutils, django module is not available.
Minor: the import paths should be updated in the files related to query.py I have a patch for this.

## Possible Solution (for bugs)

There're different ways to implement the new logging interface. One is:
`import gempython.utils.gemlogger as GEMLogger

gemlogger = GEMLogger.getGEMLogger(__name__)`

Considering the wrong python version, we can eventually alter a Makefile under gemutils

Also I propose to migrate all the DB-related python code under gempython/utils 
Currently it is spread between utils and tools. 

For the logging issue and migration I have a patch. However we still have to sort out compilation-related issue which invokes wrong version of python.
## Your Environment

* Version used: generic-amc-release-v3
* Shell used: bash

**Comment by jsturdy** [comment]
Probably the change to make the software build for both `slc6` and `cc7` is responsible for a `python` version mismatch

**Comment by mexanick** [comment]
can you provide a link to the corresponding commit?

**Comment by jsturdy** [comment]
Actually, can you post the lines that you see as wrong (and associate them with each problem, or better yet, create a separate issue for each of these bugs)?

**Comment by jsturdy** [comment]
This [e3ebf87](https://github.com/cms-gem-daq-project/cmsgemos/commit/e3ebf87b8c58af63a7b5cb1d9675769423b50bda) is probably the one that had the most significant impact on the `python` version used

**Comment by mexanick** [comment]
100%. So now my question is: how we want to solve this problem? See my comment above for proposed solutions

**Comment by jsturdy** [comment]
Can you remove all the issues not related to the `python` version and put them in a separate issue?
These are completely unrelated and should be treated as such

**Comment by mexanick** [comment]
closed this issue and opened a new one.
