### ISSUE TITLE
Wrong python version used while compiling on SLC6

### ISSUE THREAD

**Issue by mexanick** [cms-gem-daq-project/cmsgemos#133]
## Brief summary of issue

after commit e3ebf87b8c58af63a7b5cb1d9675769423b50bda
the compiler picks the system python in all cases, while it should take locally installed python2.7 for SLC6.X OS
### Types of issue

- [x ] Bug report (report an issue with the code)
- [ ] Feature request (request for change which adds functionality)

## Expected Behavior

On SLC6 should pick up non-system wide python of version 2.7.X
## Current Behavior

Compiler invokes system python which is of 2.6.6 version 

## Possible Solution (for bugs)

We can add one more env variable responsible for the version of OS, or make the XDAQ_OS var to be more than just `linux` as it is now

## Your Environment

* Version used: generic-amc-release-v3
* Shell used: bash

**Comment by jsturdy** [comment]
Migrated from #132 for solving the handling of the `python` version gracefully

**Comment by mexanick** [comment]
actually, I have more graceful and simple solution:
change lines like

`PYTHON_VERSION ?= $(shell python -c "import distutils.sysconfig;print distutils.sysconfig.get_python_version()")`

to 

`PYTHON_VERSION ?= $(shell python2.7 -c "import distutils.sysconfig;print distutils.sysconfig.get_python_version()")`

I checked, it works both in SLC6.X and CC7

**Comment by jsturdy** [comment]
Just have to make sure that the spec file makes sure that some `python2.7` version is installed

**Comment by lpetre-ulb** [comment]
Outdated issue, SLC6 is not longer supported.
