### ISSUE TITLE
HW configuration for local DB update

### ISSUE THREAD

**Issue by mexanick** [cms-gem-daq-project/cmsgemos#135]
## Brief summary of issue

Certain parameters like shelf number aren't passed to `gem::utils::db::GEMDatabaseUtils::configure`

### Types of issue

- [ ] Bug report (report an issue with the code)
- [x ] Feature request (request for change which adds functionality)

## Context (for feature requests)

Currently certain parameters as shelf used as default values. We can simply pass the needed parameters only, or eventually we can pass the full HW description from XDAQ XML config so that db query is created only for the configuration listed in that XML and we don't even try to update inactive/inexisting hardware

**Comment by mexanick** [comment]
@jsturdy , could you please point me to an example, how can I retrieve some cfg parameter from the initial XDAQ xml in GEMSupervisor.cc? I tried to look in the code, but it is still not very clear to me.

**Comment by jsturdy** [comment]
Assuming you're interested in the `shelf` parameter (which is a parameter of the `AMC13Manager`, `GLIBManager` and `OptoHybridManager`, it's not directly available in the `GEMSupervisor`.
Probably the best way to get it would be to grab the `infoSpace` object for one of those applications (most straightforward for `AMC13Manager`) and pull the parameter `crateID` out that way.
For the `AMC13Manager`, it is put into the `infoSpace` with:
```c++
p_appInfoSpace->fireItemAvailable("crateID", &m_crateID);
```
