### ISSUE TITLE
TTS_OVERRIDE register is set to 0x8 by GLIBManager

### ISSUE THREAD

**Issue by mexanick** [cms-gem-daq-project/cmsgemos#136]
## Brief summary of issue

TTS_OVERRIDE should be 0. It was required to override it before, but not anymore. We need to fix it in XDAQ configuration
### Types of issue

- [x] Bug report (report an issue with the code)
- [ ] Feature request (request for change which adds functionality)

**Comment by jsturdy** [comment]
Under what circumstances would this value need to be non-zero?  I.e., do we need a configuration parameter to pass to the manager?

**Comment by jsturdy** [comment]
Fixed by #138
