### ISSUE TITLE
gempython logging

### ISSUE THREAD

**Issue by mexanick** [cms-gem-daq-project/cmsgemos#137]
## Brief summary of issue

I have two loggers in the python code which queries the HW and updates the DB. A local logger for my amcmanager is blocking and disabling the logger from query.py. Do you know how this can be resolved?

**Comment by jsturdy** [comment]
Need details... a few line numbers will probably suffice

**Comment by mexanick** [comment]
in query.py: 
https://github.com/cms-gem-daq-project/cmsgemos/blob/07d68dc291aac5f51f9e5d12fb9e3bd38c16cac7/gempython/utils/query.py#L10-L14
then in gemamcmanager.py
https://github.com/cms-gem-daq-project/cmsgemos/blob/07d68dc291aac5f51f9e5d12fb9e3bd38c16cac7/gempython/tools/ldqm_db/amcmanager.py#L7-L8

This was changed in my pull request which is still not merged... But the main thing is: query.py has a global gemlogger, while the amcmanager has it as a local one, as a member of class. After the amcmanager logger is called, the global one from query.py is not working anymore.

**Comment by jsturdy** [comment]
Can you check in `gemlogging_config.cfg` and add the logger object definitions (for `query.py` and `amcmanager.py`), but somehow the inheritance of the loggers is not being handled properly

**Comment by jsturdy** [comment]
Actually, looks like it's a bug in the `gemlogger.py`, where
`logging.config.fileConfig(logcfg)` should be `logging.config.fileConfig(logcfg,disable_existing_loggers=False)`
Try this and see if things are looking good

I tested this on a local MWE and it allows all loggers to print messages, while the previous did not.
Configuration of the logger in the config file is not necessary, unless the defaults need to be changed (in fact, during checking this I found that it's not quite working as I would like..., so again, more work there)
Curious side effect is that the configuration of the loggers in the config file results in double logging for one of the modules..., but this can be sorted out later, if it is a problem.

**Comment by mexanick** [comment]
looks like it works! thanks!

**Comment by jsturdy** [comment]
Well, let's not close this until the PR that fixes it actually gets merged...

**Comment by mexanick** [comment]
This issue was addressed in PR https://github.com/cms-gem-daq-project/cmsgemos/pull/134
