### ISSUE TITLE
Add RCMS state reporting

### ISSUE THREAD

**Issue by jsturdy** [cms-gem-daq-project/cmsgemos#140]
## Brief summary of issue
Need to add a few parameters to applications that will report their state to RCMS

### Types of issue

- [x] Feature request (request for change which adds functionality)

## Expected Behavior
If needed, applications will provide an infospace item that RCMS can query to obtain the application FSM state

## Context (for feature requests)
RCMS requests `ReportStateToRCMS` to know whether the application will be sending asynchronous state transitions

**Comment by mexanick** [comment]
Has this been implemented?

**Comment by cgalloni** [comment]
It is implemented in the GEMSupervisor.
