### ISSUE TITLE
Composite state handling

### ISSUE THREAD

**Issue by jsturdy** [cms-gem-daq-project/cmsgemos#142]
## Brief summary of issue
The `GEMSupervisor has its own FSM (as it is a `GEMFSMApplication` but it needs to calculate its own state from the composite state of the supervised applications.
This is mostly implemented in the `GEMGlobalState` class, but in certain instances the composite state is not correct.
Additionally, we need to ensure that the state change handling is done in a robust way, such that we don't prematurely report a final state when we should still report a transitional state.

### Types of issue
- [x] Bug report (report an issue with the code)

## Expected Behavior
* The `GEMSupervisor` FSM state will reflect the composite state of the children at all times
* An inhibition of the `GEMSupervisor` FSM state should be ensured at the initial transition

**Comment by mexanick** [comment]
Has this been implemented?

**Comment by cgalloni** [comment]
Cleaning of the FSM states is ongoing in the GitLab development.
