### ISSUE TITLE
Bug Report: Infinite Loop in getUltraScanResults(...)

### ISSUE THREAD

**Issue by bdorney** [cms-gem-daq-project/cmsgemos#149]
## Brief summary of issue

When taking threshold scans with `vfatqc-python-scripts/ultraThreshold.py` it looks like an inifinite loop in `getUltraScanResults(...)` occurs at [L707](https://github.com/cms-gem-daq-project/cmsgemos/blob/ab771dd9cda1e946cdc120e0a99096f312217027/gempython/tools/optohybrid_user_functions_uhal.py#L707).

```
    while (readRegister(device,"%s.MONITOR.STATUS"%(scanBase)) > 0):
```

This seems to always evaluate to greater than 0.  Observed both on the user account of `cosmicstandtif` and also as myself running the coffin setup.

### Types of issue

- [X] Bug report (report an issue with the code)
- [ ] Feature request (request for change which adds functionality)

## Expected Behavior

Loop should not be infinite.

## Current Behavior

Loop is infinite causing scan to not advance.

### Steps to Reproduce (for bugs)

1. Configure Detector
2. Launch a threshold scan with `ultraThreshold.py` the `--debug` option

If the `--debug` option is not used it looks like the scan hangs.

See scan command executed and produced log files:

```
ultraThreshold.py -s2 -g0 --shelf=1 --nevts=1000 --vfatmask=0xf40400 --vt2=0 --perchannel --filename=/data/bigdisk/GEM-Data-Taking/GE11_QC8//GE11-VI-L-CERN-0002/threshold/channel/2017.09.20.17.13/ThresholdScanData.root --debug 2>&1 | tee "threshScanWithDebug.txt"
```
[threshScanWithDebug_coffinSetup.txt](https://github.com/cms-gem-daq-project/cmsgemos/files/1318260/threshScanWithDebug_coffinSetup.txt)

```
python /home/GE11COSMICS/Software/DAQ/vfatqc-python-scripts/ultraThreshold.py -s2 -g0 --shelf=3 --nevts=1000 --vfatmask=0xf40400 --vt2=0 --perchannel --filename=/data/bigdisk/GEM-Data-Taking/GE11_QC8//GE11-VI-L-CERN-0001/threshold/channel/2017.09.20.16.31/ThresholdScanData.root --debug 2>&1 | tee "threshScanWithDebug_Trial2_QC8.txt"
```
[threshScanWithDebug_Trial2_QC8.txt](https://github.com/cms-gem-daq-project/cmsgemos/files/1318256/threshScanWithDebug_Trial2_QC8.txt)

## Your Environment

* Version used (coffin setup): ab771dd9cda1e946cdc120e0a99096f312217027
* Version used (qc8): ab771dd9cda1e946cdc120e0a99096f312217027
* Shell used (coffin setup): /bin/zsh
* Shell used (qc8): /bin/bash

**Comment by jsturdy** [comment]
Seems possibly related to not setting the trigger source in `ultraThreshold`, though to be confirmed
As a result, PR #150 presents a new way to get partial results throughout the scan, though it is not clear if it is useful/relevant based on the fact that a scan stopped midway through will not return the partial results

**Comment by jsturdy** [comment]
Closing as invalid
