### ISSUE TITLE
Ensure software puts hardware into proper state at each transition

### ISSUE THREAD

**Issue by jsturdy** [cms-gem-daq-project/cmsgemos#154]
## Brief summary of issue
Need to make sure that at each FSM transition, the hardware is in the expected state
* Can be ensured by software **or** firmware, but needs to be done

### Types of issue
- [x] Compatibility request (request for change which ensures compatibility)

## Expected Behavior
Some notes from the `TCDS`/`DAQ` [operation pages](https://twiki.cern.ch/twiki/bin/view/CMS/DAQ-subdet-cdaq-synchronization)
* **Before reporting `Configured` all events shall be purged from the buffers. In particular this also holds in the transition from running to configured in the case of a run abort, and the last events are not necessarily taken out by `cdaq`.**

**Comment by cgalloni** [comment]
@jsturdy , do you remember if this was implemented?

**Comment by jsturdy** [comment]
Given that data was successfully taken for the slice test, I'd say yes

**Comment by cgalloni** [comment]
Thanks!
