### ISSUE TITLE
UHAL updates

### ISSUE THREAD

**Issue by jsturdy** [cms-gem-daq-project/cmsgemos#174]
## Brief summary of issue
Upstream changes in the `uhal` library have some changes in the pipeline

### Types of issue
- [x] External compatibility (change to maintain compatibility with external library)

```
/opt/cactus/include/uhal/Utilities.hpp:11:2: warning: #warning The header file "uhal/Utilities.hpp" has now been deprecated, and will be removed in a future uHAL release. The functions declared therein have been moved to "uhal/utilities/bits.hpp", "uhal/utilities/files.hpp" and "uhal/utilities/xml.hpp". [-Wcpp]
 #warning The header file "uhal/Utilities.hpp" has now been deprecated, and will be removed in a future uHAL release. The functions declared therein have been moved to "uhal/utilities/bits.hpp", "uhal/utilities/files.hpp" and "uhal/utilities/xml.hpp".
```
## Context
* `uhal` version `2.4` does not implement the change
* `uhal` version `2.5` implements the change, but maintains backwards compatibility
* `uhal` version `2.6` implements the change fully, and removes backwards compatibility

## Your Environment
* `slc6` with `uhal 2.4` - current code works
* `cc7` with `uhal 2.5` - current code works, with warning
* `cc7` with `uhal 2.6` - current code fails to compile, as migration has been implemented

**Comment by lpetre-ulb** [comment]
Shall this issue be closed? If I'm not mistaken, `cmsgemos` now compiles properly with `uhal` 2.6 (and maybe even 2.7).

**Comment by jsturdy** [comment]
Yes, provided there is an `amc13` build against `2.7` our code *should* build fine
