### ISSUE TITLE
Bug Report: linkuhaltables.sh does not create correct links.

### ISSUE THREAD

**Issue by bdorney** [cms-gem-daq-project/cmsgemos#178]
## Brief summary of issue

Cannot make uhal links with `linkuhaltables.sh` due to syntax differences between address table filenames in the release and expectation in `linkuhaltables.sh`

### Types of issue

- [X] Bug report (report an issue with the code)
- [ ] Feature request (request for change which adds functionality)

## Expected Behavior

`linkuhaltables.sh` should conform to the syntax of files in a FW release or...
`GEM_AMC` should have an automated release procedure that maintains a filename convention.  However the last two releases in `GEM_AMC` use the same syntax for the address table filenames, e.g.

- [v1.11.6](https://github.com/evka85/GEM_AMC/releases/tag/v1.11.6)
- [v1.9.4](https://github.com/evka85/GEM_AMC/releases/tag/v1.9.4)

## Current Behavior

```
$ ./linkuhaltables.sh $FIRMWARE_GEM/CTP7/v1.11.6/address_table_v1_11_6 ""
ln -fs /data/bigdisk/GEMDAQ_Documentation/system/firmware/files/CTP7/v1.11.6/address_table_v1_11_6/uhal_gem_amc_ctp7__AMC.xml uhal_gem_amc_ctp7_amc.xml
ln -fs /data/bigdisk/GEMDAQ_Documentation/system/firmware/files/CTP7/v1.11.6/address_table_v1_11_6/uhal_gem_amc_ctp7__OH00.xml uhal_gem_amc_ctp7_link00.xml
ln -fs /data/bigdisk/GEMDAQ_Documentation/system/firmware/files/CTP7/v1.11.6/address_table_v1_11_6/uhal_gem_amc_ctp7__OH01.xml uhal_gem_amc_ctp7_link01.xml
ln -fs /data/bigdisk/GEMDAQ_Documentation/system/firmware/files/CTP7/v1.11.6/address_table_v1_11_6/uhal_gem_amc_ctp7__OH02.xml uhal_gem_amc_ctp7_link02.xml
ln -fs /data/bigdisk/GEMDAQ_Documentation/system/firmware/files/CTP7/v1.11.6/address_table_v1_11_6/uhal_gem_amc_ctp7__OH03.xml uhal_gem_amc_ctp7_link03.xml
ln -fs /data/bigdisk/GEMDAQ_Documentation/system/firmware/files/CTP7/v1.11.6/address_table_v1_11_6/uhal_gem_amc_ctp7__OH04.xml uhal_gem_amc_ctp7_link04.xml
ln -fs /data/bigdisk/GEMDAQ_Documentation/system/firmware/files/CTP7/v1.11.6/address_table_v1_11_6/uhal_gem_amc_ctp7__OH05.xml uhal_gem_amc_ctp7_link05.xml
ln -fs /data/bigdisk/GEMDAQ_Documentation/system/firmware/files/CTP7/v1.11.6/address_table_v1_11_6/uhal_gem_amc_ctp7__OH06.xml uhal_gem_amc_ctp7_link06.xml
ln -fs /data/bigdisk/GEMDAQ_Documentation/system/firmware/files/CTP7/v1.11.6/address_table_v1_11_6/uhal_gem_amc_ctp7__OH07.xml uhal_gem_amc_ctp7_link07.xml
ln -fs /data/bigdisk/GEMDAQ_Documentation/system/firmware/files/CTP7/v1.11.6/address_table_v1_11_6/uhal_gem_amc_ctp7__OH08.xml uhal_gem_amc_ctp7_link08.xml
ln -fs /data/bigdisk/GEMDAQ_Documentation/system/firmware/files/CTP7/v1.11.6/address_table_v1_11_6/uhal_gem_amc_ctp7__OH09.xml uhal_gem_amc_ctp7_link09.xml
ln -fs /data/bigdisk/GEMDAQ_Documentation/system/firmware/files/CTP7/v1.11.6/address_table_v1_11_6/uhal_gem_amc_ctp7__OH10.xml uhal_gem_amc_ctp7_link10.xml
ln -fs /data/bigdisk/GEMDAQ_Documentation/system/firmware/files/CTP7/v1.11.6/address_table_v1_11_6/uhal_gem_amc_ctp7__OH11.xml uhal_gem_amc_ctp7_link11.xml
```

This generates a series of broken links.  Seems like the address table xml's inside the CTP7 releases
- [v1.11.6](https://github.com/evka85/GEM_AMC/releases/tag/v1.11.6)
- [v1.9.4](https://github.com/evka85/GEM_AMC/releases/tag/v1.9.4)

Use the following format:

```
$ ll address_table_v1_11_6
total 20M
-rw-rw-r--. 1 gemuser gemuser 825K Aug 29  2017 uhal_gem_amc_glib.xml
-rw-rw-r--. 1 gemuser gemuser 5.2M Aug 29  2017 uhal_gem_amc_ctp7.xml
-rw-rw-r--. 1 gemuser gemuser 172K Nov 14 21:17 gem_amc_top.xml
-rw-rw-r--. 1 gemuser gemuser 1.1M Nov 14 21:24 uhal_gem_amc_ctp7_link03.xml
-rw-rw-r--. 1 gemuser gemuser 1.1M Nov 14 21:24 uhal_gem_amc_ctp7_link02.xml
-rw-rw-r--. 1 gemuser gemuser 1.1M Nov 14 21:24 uhal_gem_amc_ctp7_link01.xml
-rw-rw-r--. 1 gemuser gemuser 1.1M Nov 14 21:24 uhal_gem_amc_ctp7_link00.xml
-rw-rw-r--. 1 gemuser gemuser 164K Nov 14 21:24 uhal_gem_amc_ctp7_amc.xml
-rw-rw-r--. 1 gemuser gemuser 1.1M Nov 14 21:24 uhal_gem_amc_ctp7_link11.xml
-rw-rw-r--. 1 gemuser gemuser 1.1M Nov 14 21:24 uhal_gem_amc_ctp7_link10.xml
-rw-rw-r--. 1 gemuser gemuser 1.1M Nov 14 21:24 uhal_gem_amc_ctp7_link09.xml
-rw-rw-r--. 1 gemuser gemuser 1.1M Nov 14 21:24 uhal_gem_amc_ctp7_link08.xml
-rw-rw-r--. 1 gemuser gemuser 1.1M Nov 14 21:24 uhal_gem_amc_ctp7_link07.xml
-rw-rw-r--. 1 gemuser gemuser 1.1M Nov 14 21:24 uhal_gem_amc_ctp7_link06.xml
-rw-rw-r--. 1 gemuser gemuser 1.1M Nov 14 21:24 uhal_gem_amc_ctp7_link05.xml
-rw-rw-r--. 1 gemuser gemuser 1.1M Nov 14 21:24 uhal_gem_amc_ctp7_link04.xml
```

But the format that `linkuhaltables.sh` is coded for uses:

```
uhal_gem_amc_ctp7_${subname}_OH${linknum}.xml
```

Specifically in the release `${subname}` is not present and `OH${linknum}` is `link${linknum}`.

### Steps to Reproduce (for bugs)

1. `wget https://github.com/evka85/GEM_AMC/releases/download/v1.11.6/address_table_v1_11_6.zip`
2.  `unzip address_table_v1_11_6.zip`
3.  `./linkuhaltables.sh address_table_v1_11_6 ""`

## Possible Solution (for bugs)

Change `linkuhaltables.sh` to match the syntax of the address tables in a `GEM_AMC` release format.  

## Context

Cannot link uhal tables automatically on a new setup or new FW release version.

## Your Environment

* Version used: da92e0d5493e3713307901c5afae2f83f32a1787
* Shell used: `/bin/bash`

**Comment by bdorney** [comment]
seems like also script is expecting `uhal_gem_amc_ctp7__AMC.xml` but in the release there is only `uhal_gem_amc_ctp7_amc.xml`

**Comment by jsturdy** [comment]
If the address table names in the zip file are all normalized (and matching what the software is expecting), then there is no need for the script, one can simply execute:
```
ln -s /path/to/unzipped/address/uhal*.xml $GEM_ADDRESS_TABLE_PATH/
```

**Comment by bdorney** [comment]
Closing as irrelevant in post packaging world
