### ISSUE TITLE
New tag not triggering travis build

### ISSUE THREAD

**Issue by jsturdy** [cms-gem-daq-project/cmsgemos#183]
## Brief summary of issue
Pushed a new tag this evening but no corresponding travis build was triggered.
Pushed the same tag to my own remote and the build triggered

### Types of issue

- [x] Bug report (report an issue with the code)

## Expected Behavior
Push a tag, generate a build

## Current Behavior
Push a tag, no build generated

**Comment by jsturdy** [comment]
Seems due to repository settings, will know for sure with next PR/tag push

**Comment by jsturdy** [comment]
Secondary issue is moving and creating files between the `docker` container and the `travis` VM, currently breaking the creating of `RPM` tarballs to upload, rather than many individual `RPM`s

**Comment by mexanick** [comment]
@jsturdy is this resolved? Looks like stale issue

**Comment by lpetre-ulb** [comment]
Was Travis CI ever used in production? The [project referenced in the README](https://travis-ci.org/travis-ci.org/cms-gem-daq-project/cmsgemos) does not seem to exist anymore. Closing the issue, feel free to reopen it if needed.
