### ISSUE TITLE
Bug report: xdaq is calling confChamber.py with hardcoded chamber filenames

### ISSUE THREAD

**Issue by AndrewLevin** [cms-gem-daq-project/cmsgemos#186]
While running xdaq on gem904qc8daq, we found that it was trying to configure chambers using configuration files like chConfig_GEMINIm01L2.txt, which do not exist on our machine.

We see error messages such as

```
Error in <TTree::ReadFile>: Cannot open file: /data/bigdisk/GEM-Data-Taking/GE11_QC8//configs/z4.0/chConfig_GEMINIm30L2.txt
Error in <TTree::ReadFile>: Cannot open file: /data/bigdisk/GEM-Data-Taking/GE11_QC8//configs/z4.0/vfatConfig_GEMINIm29L1.txt
VFATs set to run mode
```
in the our xdaq log file /home/gemuser/gemdaq/xdaq_log_Cosmics_2018.07.06.14.15.05.txt  on gem904qc8daq.cern.ch

### Types of issue

- [x] Bug report (report an issue with the code)
- [ ] Feature request (request for change which adds functionality)

### Steps to Reproduce (for bugs)
1. ssh to gem904qc8daq.cern.ch as gemuser
2.  xdaq.sh -lWARN -p5056 -c /home/gemuser/gemdaq/cosmic_stand_data_taking_lemo_triggers_tif.xml
3. Press Initialize in xdaq
4. Press Configure in xdaq

## Context
We are configuring using python scripts, and we did not realize that xdaq was even running confChamber.py, but we noticed error messages about configuration files not found when we ran xdaq.

## Your Environment
We are working as gemuser on gem904qc8daq.cern.ch

**Comment by jsturdy** [comment]
The `xdaq` code is calling `confAllChambers.py -s<slot> --ztrim=4 --vt1bump=10 --config --run`, and it will stay this way for the near term as it is the most convenient for P5 data taking (and *should* be compatible with other setups, provided they simply put the desired configuration files in the expected location)
