### ISSUE TITLE
`query.py` broken

### ISSUE THREAD

**Issue by jsturdy** [cms-gem-daq-project/cmsgemos#187]
## Brief summary of issue
`gempython/utils/db/query.py` is [badly broken](https://github.com/cms-gem-daq-project/cmsgemos/blame/generic-amc-release-v3/gempython/utils/db/query.py), probably the result of a bad merge/rebase

I think we noticed this before, but must not have fixed it fully (it gets patched at P5 for the specifics there)

@mexanick I just need a quick guidance on what this should look like (or the last known "good" version), if you have 5 minutes, otherwise, we'll sort it out when you're back

**Comment by mexanick** [comment]
Obsolete
