### ISSUE TITLE
GEM online DB configuration objects

### ISSUE THREAD

**Issue by jsturdy** [cms-gem-daq-project/cmsgemos#213]
## Brief summary of issue
There is a new branch `feature/gemonlinedb` that contains the new `gemonlinedb` package structure.
This package is going to aim to provide the interface between the online software and the online DB (and configuration documents).
For further context, see the parent [project](https://github.com/orgs/cms-gem-daq-project/projects/6)

### Types of issue
- [x] Feature request (request for change which adds functionality)

This issue should focus solely on creating the `c++` objects that will hold the configuration information extracted from `DB/XML` sources.

## Contributing
* Create branch off of `feature/gemonlinedb` and make PRs to this branch.
* There is some that was previously developed to begin this process, see the parent [project](https://github.com/orgs/cms-gem-daq-project/projects/6)
* When the feature is more or less complete, it will be merged into/rebased onto `develop`/an appropriate release target

**Comment by lmoureaux** [comment]
In the xml templates there are fields like this (from the VFAT3 chip configuration):
```xml
<GLB_CAL_CFG_CTRL_NAME>GLB_CAL1_CFG_CTRL</GLB_CAL_CFG_CTRL_NAME>
<GLB_CAL_CFG_CTRL_VALUE>100</GLB_CAL_CFG_CTRL_VALUE>
```
Two values of `_NAME` are used in the template, but only one per `<DATA>` block:

* `GLB_CAL0_CFG_CTRL`
* `GLB_CAL1_CFG_CTRL`

From the VFAT3 manual, I understand that they correspond to two complementary registers, `GBL CFG CAL 0` and `GBL CFG CAL 1`. They are mapped to two different columns in the database.

Does any one know why these fields ended up being grouped in the `xml` templates, and only one is apparently supposed to be used at a time? Or who can I contact?

**Comment by jsturdy** [comment]
* This template *might* be outdated (we had specifically requested that this duplication of `NAME` `VALUE` be removed), @mexanick did I upload an older version? Or possibly we didn't get a new one following our feedback from Imran?
* The "template" that is uploaded I think is not a proper "template", rather, an example of how the data could be placed... (I'm looking at some previous code I wrote for a different subsystem and the templates there are in fact proper templates)
  * See, e.g., [base template](https://gist.github.com/jsturdy/a1c07c4287905bd14325ac3eebdf7243), [dataset definition](https://gist.github.com/jsturdy/8034d9b68242efbd5d2f0ee5186a42b2), [channel block](https://gist.github.com/jsturdy/038dd5618774509dc959d9e4958f26b8), [data block](https://gist.github.com/jsturdy/05a979bee051e349e56f613b31f390ed), and example full [output](https://gist.github.com/jsturdy/ec23e312aa2c4b5f8fc4aa51299c87e7) from the code that uses the aforementioned templates to create a full uploadable dataset.

**Comment by jsturdy** [comment]
@lmoureaux, for how I have currently hooked the HW to these configuration objects, see, e.g., [this (config object filler)](https://github.com/jsturdy/cmsgemos/blob/subfeature/hw-db-interface/gemhardware/src/common/optohybrid/OptoHybridManager.cc#L699), [this (HW object current register dumper)](https://github.com/jsturdy/cmsgemos/blob/subfeature/hw-db-interface/gemhardware/src/common/optohybrid/HwOptoHybrid.cc#L299), and [this (`BLASTER` RAM reader/writer)](https://github.com/jsturdy/cmsgemos/blob/subfeature/hw-db-interface/gemhardware/src/common/HwGenericAMC.cc#L904)

My current thinking is this:
* HW device library should be decoupled from almost anything else - precludes including the dump to configuration object here
  * This is because I would *like* for a minimal setup to include the HW device library and the `python` library and be able to have a minimally working setup, later packages can be installed for additional features (`managers` and `onlinedb` to add the configuration objects)
* The HW manager library can provide this link easily, so it has been initially implemented here

Please let me know if my usage is clear, and if you have any thoughts.

**Comment by lmoureaux** [comment]
Here are a few items from a cursory look at your code:

1. Instead of passing integers around, we could have special classes `AMC13Address`, ..., `VFATAddress` that would encapsulate them. A `VFATAddress` would be an `OHAddress` plus the VFAT ID, etc. Bounds can be checked automatically so one can't have an address pointing to VFAT 24. One could also define iterators...
2. Check pointers! The following code is super dangerous:
    ```C++
    auto ohCfg = gem::onlinedb::ConfigurationManager::getConfiguration(lock)
        // ->getAMC13Config(shelf)
        .at(shelf)
        ->getAMCConfig(slot)
        ->getOHConfig(ohN);
    ```
2. I agree that `.at(shelf)` looks out-of-place.
3. I would advise against using the `detail::RegisterData` interface. Despite being public, it's really meant for internal use and will likely change with the final DB design.
4. `setBxnOffset` can be changed to `setBXNOffset` in [the JSON file](https://github.com/jsturdy/cmsgemos/blob/subfeature/hw-db-interface/gemonlinedb/defs/OHv3Configuration.json#L8) (rebase first since it was changed in the GBTX PR):
    ```json
    {
        "name": "BXN_OFFSET",
        "cpp name": "BXNOffset"
    }
    ```
5. We could tweak the memory layout of the configuration objects to allow for `memcpy()`'ing the contents. It's a bit dangerous though...

The configuration objects could very well live outside of `onlinedb`.

I don't see any parallel code nor any place where the configuration objects are read (ie you always request an `EditLock`). Do you plan to implement reading and writing in symmetric ways?

**Comment by jsturdy** [comment]
> Here are a few items from a cursory look at your code:
> 
> 1. Instead of passing integers around, we could have special classes `AMC13Address`, ..., `VFATAddress` that would encapsulate them. A `VFATAddress` would be an `OHAddress` plus the VFAT ID, etc. Bounds can be checked automatically so one can't have an address pointing to VFAT 24. One could also define iterators...

I'm not sure what you're proposing here, referencing specific places where this should be donE would be helpful.

> 2. Check pointers! The following code is super dangerous:
>    ```c++
>    auto ohCfg = gem::onlinedb::ConfigurationManager::getConfiguration(lock)
>        // ->getAMC13Config(shelf)
>        .at(shelf)
>        ->getAMCConfig(slot)
>        ->getOHConfig(ohN);
>    ```

Indeed, I would much rather have something like (similarly for other device configurations):
```c++
auto ohCfg = gem::onlinedb::ConfigurationManager::getOHConfig(lock,shelf,slot,ohN)
```
that would `throw` an exception in the case of a failure.

> 3. I agree that `.at(shelf)` looks out-of-place.
> 4. I would advise against using the `detail::RegisterData` interface. Despite being public, it's really meant for internal use and will likely change with the final DB design.

Indeed, I didn't want to have to know anything about the `detail::` code, however, this seemed like the only current way to implement things.
This aspect is definitely a place where I think some improvement is needed, i.e., passing the *actual* register data into the configuration object.

> 5. `setBxnOffset` can be changed to `setBXNOffset` in [the JSON file](https://github.com/jsturdy/cmsgemos/blob/subfeature/hw-db-interface/gemonlinedb/defs/OHv3Configuration.json#L8) (rebase first since it was changed in the GBTX PR):
>    ```json
>    {
>        "name": "BXN_OFFSET",
>        "cpp name": "BXNOffset"
>    }
>    ```

Right I need to do this...

> 6. We could tweak the memory layout of the configuration objects to allow for `memcpy()`'ing the contents. It's a bit dangerous though...
> 
> The configuration objects could very well live outside of `onlinedb`.

Indeed, while working through this, I thought a little about how to make the structure "best"
If both `gemhardware_devices` and `gemonlinedb` need to know about them, but we don't want to link one to the other (which has been my gut instinct), then the only place is in the `gemutils` package
Lately, I've started leaning towards the config object definition existing in the HW device library, since that will make the `gemonlinedb` dependent no the HW devices but not vice versa, and the link in that direction makes more structural and semantic sense (the `gemonlinedb` is really trying to describe a HW device)
Let me know what you think.
My primary driver is to keep `gemhardware_devices` as minimal as possible, with as few dependencies as possible.

> 
> I don't see any parallel code nor any place where the configuration objects are read (ie you always request an `EditLock`). Do you plan to implement reading and writing in symmetric ways?

My plan is that the code currently done in a loop (over AMCs and OptoHybrids) will be parallelized at the level of the AMC, because it is only up to this level that true parallel actions can be done with the hardware.

**Comment by lmoureaux** [comment]
>> Instead of passing integers around, we could have special classes AMC13Address, ..., VFATAddress that would encapsulate them. A VFATAddress would be an OHAddress plus the VFAT ID, etc. Bounds can be checked automatically so one can't have an address pointing to VFAT 24. One could also define iterators...
>
> I'm not sure what you're proposing here, referencing specific places where this should be donE would be helpful.

Virtually every function taking `int self, int slot, int ohN, int vfat` could be changed to take `const VFATAddress &addr`. Easier to write, easier to catch the intent.

>> I would advise against using the detail::RegisterData interface. Despite being public, it's really meant for internal use and will likely change with the final DB design.
>
> Indeed, I didn't want to have to know anything about the detail:: code, however, this seemed like the only current way to implement things.
> This aspect is definitely a place where I think some improvement is needed, i.e., passing the actual register data into the configuration object.

[This Doxygen build](http://homepage.iihe.ac.be/~lmoureau/GEM/cmsgemos/doc/build/html/d8/d80/classgem_1_1onlinedb_1_1detail_1_1_v_f_a_t3_chip_configuration_gen.html#pub-methods) is a bit outdated but the methods are there, "hidden" in a `Gen` class -- didn't find how to force Dox to copy the docs. Apart that I didn't pay attention to the naming convention (was mentioned in the relevant PRs), how do you think it should be improved?

>> The configuration objects could very well live outside of `onlinedb`.
>
> [...] Let me know what you think.

Not sure what the exact roles of the various libraries are (esp. `gembase` vs `gemutils`), but being able to describe the configuration of a device sounds like a good feature to have in a lib whose primary intent is to work with these devices.

I will in any case factor out the `read/writeRegisterData` part from the objects (the methods only use the public interface, so can be free functions).
Since it knows about all registers, I think `parseDef.py` could be extended to generate the code writing (and reading) blaster blobs.

**Comment by jsturdy** [comment]
> > > Instead of passing integers around, we could have special classes AMC13Address, ..., VFATAddress that would encapsulate them. A VFATAddress would be an OHAddress plus the VFAT ID, etc. Bounds can be checked automatically so one can't have an address pointing to VFAT 24. One could also define iterators...
> > 
> > 
> > I'm not sure what you're proposing here, referencing specific places where this should be done would be helpful.
> 
> Virtually every function taking `int self, int slot, int ohN, int vfat` could be changed to take `const VFATAddress &addr`. Easier to write, easier to catch the intent.

I see... I would not prioritize this at the present time.

> 
> > > I would advise against using the detail::RegisterData interface. Despite being public, it's really meant for internal use and will likely change with the final DB design.
> > 
> > 
> > Indeed, I didn't want to have to know anything about the detail:: code, however, this seemed like the only current way to implement things.
> > This aspect is definitely a place where I think some improvement is needed, i.e., passing the actual register data into the configuration object.
> 
> [This Doxygen build](http://homepage.iihe.ac.be/~lmoureau/GEM/cmsgemos/doc/build/html/d8/d80/classgem_1_1onlinedb_1_1detail_1_1_v_f_a_t3_chip_configuration_gen.html#pub-methods) is a bit outdated but the methods are there, "hidden" in a `Gen` class -- didn't find how to force Dox to copy the docs. Apart that I didn't pay attention to the naming convention (was mentioned in the relevant PRs), how do you think it should be improved?

Here I was mainly commenting on the fact that (as I understand them) anything inside the `detail::` namespace should not be part of the public API, and I shouldn't need to get things from there to interface with the objects.
However, it is the only way currently...

> 
> > > The configuration objects could very well live outside of `onlinedb`.
> > 
> > 
> > [...] Let me know what you think.
> 
> Not sure what the exact roles of the various libraries are (esp. `gembase` vs `gemutils`), but being able to describe the configuration of a device sounds like a good feature to have in a lib whose primary intent is to work with these devices.

* `gembase` is supposed to hold everything that other GEM applications derive from, e.g., `GEMSupervisor`
* `gemutils` is supposed to hold generic utilities that (hopefully) do not bring in (m)any dependencies; currently this does bring in some extra (`xdaq`) stuff, and I would like to migrate that stuff into `gembase`, but that's currently todo.

> 
> I will in any case factor out the `read/writeRegisterData` part from the objects (the methods only use the public interface, so can be free functions).
> Since it knows about all registers, I think `parseDef.py` could be extended to generate the code writing (and reading) blaster blobs.

`parseDef.py` currently knows about config DB columns, not necessarily about registers (I hadn't wanted to put this into the DB because I didn't want that additional dependency, as this should really only matter at the SW to HW interface level, via the address table)
Provided there is a 1-to-1 mapping between the column names and a node in the address table (which we require by design), this is a solvable issue; however, all of this should *not* happen outside of the HW device class library.
I haven't settled on a design for this as I've worked this up, just a few, incomplete, insufficient options.

**Comment by lmoureaux** [comment]
> Here I was mainly commenting on the fact that (as I understand them) anything inside the detail:: namespace should not be part of the public API, and I shouldn't need to get things from there to interface with the objects.

I see... let me clarify. The public API of a class outside of `detail::` is not an implementation detail. The fact that part of it is inherited from the a `Gen` class is a detail (and is subject to change without notice). Ideally, you shouldn't know about the `Gen` classes and see only the public methods of the configuration objects.

**Comment by jsturdy** [comment]
> I see... let me clarify. The public API of a class outside of `detail::` is not an implementation detail. The fact that part of it is inherited from the a `Gen` class is a detail (and is subject to change without notice). Ideally, you shouldn't know about the `Gen` classes and see only the public methods of the configuration objects.

Yes, this I (think I) understood, but my point was that to do almost anything with the configuration object currently, one *requires* the details (here I mean function names and signatures) *from* the `detail::` class, which as you state, should not be the case (though perhaps you are *only* referring to the implementation of the functions, rather than the names and signatures).
I agree that the *implementation* details should not matter from the use case we are discussing here (or really any use of these configuration objects), because this use case is simply an interface *to* a config object.

As I see it, for the HW case what is needed is only:
* Take configuration object and write it to HW RAM (this is a continuous block of 32-bit words, in some "well-known" ordering, e.g., sequential registers for `GBT`/`VFAT`, specific registers for `AMC`/`OptoHybrid`)
  * This does not seem to be possible without the `detail::` class information, but should be easy to implement in the public API with a `exportBLOB` function, the care is just to make sure that the `BLOB` mapping is correct, and only done in one place...
* Read the HW RAM and put into a config object
  * This does not seem to be possible without the `detail::` class information
  * Likewise, should be easy to implement in the public API with a `importBLOB` function, and again, the care is just to make sure that the `BLOB` mapping is correct, and only done in one place...
* Read the HW component registers and put into a config object
  * This does not seem to be possible without the `detail::` class information
  * This could either be done by first translating the registers into a `BLOB` and then using one of the aforementioned functions, or by some additional function that would possibly take a `map` object
  * Related to this last point, the two aforementioned functions *could* also simply export/import a `map` object, offloading the mapping of name to register to the HW device class, which should know this from the address table, and this could be implemented in the non-`detail::` portion of the config object class

I think this aspect of things we should take the most care with, as it is likely to be the most critical portion of the configuration flow.

**Comment by lmoureaux** [comment]
>>>> Instead of passing integers around, we could have special classes AMC13Address, ..., VFATAddress that would encapsulate them. A VFATAddress would be an OHAddress plus the VFAT ID, etc. Bounds can be checked automatically so one can't have an address pointing to VFAT 24. One could also define iterators...
>>>
>>> I'm not sure what you're proposing here, referencing specific places where this should be done would be helpful.
>>
>>Virtually every function taking int self, int slot, int ohN, int vfat could be changed to take const VFATAddress &addr. Easier to write, easier to catch the intent.
>
> I see... I would not prioritize this at the present time.

Where would such classes live? In `gemutils`?

**Comment by jsturdy** [comment]
> > > > > Instead of passing integers around, we could have special classes AMC13Address, ..., VFATAddress that would encapsulate them. A VFATAddress would be an OHAddress plus the VFAT ID, etc. Bounds can be checked automatically so one can't have an address pointing to VFAT 24. One could also define iterators...
> > > > 
> > > > 
> > > > I'm not sure what you're proposing here, referencing specific places where this should be done would be helpful.
> > > 
> > > 
> > > Virtually every function taking int self, int slot, int ohN, int vfat could be changed to take const VFATAddress &addr. Easier to write, easier to catch the intent.
> > 
> > 
> > I see... I would not prioritize this at the present time.
> 
> Where would such classes live? In `gemutils`?

Until it becomes an accepted feature, if you want to use something like this, then I'd suggest putting it inside the private `detail` interface where appropriate, such that the current indexing is not affected.
