### ISSUE TITLE
Fill xml templates

### ISSUE THREAD

**Issue by jsturdy** [cms-gem-daq-project/cmsgemos#214]
## Brief summary of issue
There is a new branch `feature/gemonlinedb` that contains the new `gemonlinedb` package structure.
This package is going to aim to provide the interface between the online software and the online DB (and configuration documents).
For further context, see the parent [project](https://github.com/orgs/cms-gem-daq-project/projects/6)

### Types of issue
- [x] Feature request (request for change which adds functionality)

This issue should focus solely on creating the `xml` documents from the `xml` templates provided by the DB group, from the configuration objects in #213 

## Contributing
* Create branch off of `feature/gemonlinedb` and make PRs to this branch.
* There is some that was previously developed to begin this process, see the parent [project](https://github.com/orgs/cms-gem-daq-project/projects/6)
* When the feature is more or less complete, it will be merged into/rebased onto `develop`/an appropriate release target

**Comment by jsturdy** [comment]
Can't attach the templates here it seems, and also have some things that might need to be updated, but I'll put them in the `feature/gemonlinedb` branch

**Comment by lmoureaux** [comment]
Will use JSON. Files can be created with only minor adjustments needed to upload them.
