### ISSUE TITLE
Configuration reader

### ISSUE THREAD

**Issue by jsturdy** [cms-gem-daq-project/cmsgemos#215]
## Brief summary of issue
There is a new branch `feature/gemonlinedb` that contains the new `gemonlinedb` package structure.
This package is going to aim to provide the interface between the online software and the online DB (and configuration documents).
For further context, see the parent [project](https://github.com/orgs/cms-gem-daq-project/projects/6)

### Types of issue
- [x] Feature request (request for change which adds functionality)

This issue should focus solely on creating the `reader` application, that can read from either an `xml` document source (created from #214), a DB file dump, or a DB query.
It should create the configuration objects in #213 

## Contributing
* Create branch off of `feature/gemonlinedb` and make PRs to this branch.
* There is some that was previously developed to begin this process, see the parent [project](https://github.com/orgs/cms-gem-daq-project/projects/6)
* When the feature is more or less complete, it will be merged into/rebased onto `develop`/an appropriate release target

**Comment by cgalloni** [comment]
Development moved to GitLab.
