### ISSUE TITLE
Discussion: xdaq state transitions & v3 hardware

### ISSUE THREAD

**Issue by bdorney** [cms-gem-daq-project/cmsgemos#217]
## Brief summary of issue

@jsturdy asked me to make a list of "new" v3 hardware specific actions that are necessary during xdaq state transitions.  Given this is a debugging process I think I will semi-regularly update/reply to this issue as things come up. 

### Types of issue

- [ ] Bug report (report an issue with the code)
- [X] Feature request (request for change which adds functionality)

## Current Working Procedure

Procedure here is specific to `eagle26` on `gem904qc8daq`. To successfully initiate xdaq state transitions and get to data-taking the following is necessary:

1. Launch `xdaq`:
```bash
xdaq.sh -lINFO -p5056 -c $PWD/gemsupervisor_V3_test.xml 2>&1 | tee xdaq_log_v3Test.txt
```
2. Navigate to gemsupervisor hyperdaq page,
3. Press `Initialize` (wait),
4. Press `Configure` (wait),
5. Go to `xdaq` terminal and when prompted provide CTP7 `texas` password for dummy phase align script execution,
6. Wait until all managers reach `Configured`.
7. Write `INPUT_ENABLE_MASK` to match number of OH's that you want to readout, e.g. :
```
eagle26 > write GEM_AMC.DAQ.CONTROL.INPUT_ENABLE_MASK <ohMask>
```
8. Check that `GEM_AMC.TTC.GENERATOR.ENABLE` is set to `0x0`.
9. Press `Start`
10. Check that `L1A_ENABLE` is set to `0x1`.

Data writes to disk.

## Your Environment

```bash
Installed Packages
Name        : cmsgemos-gembase
Arch        : x86_64
Version     : 0.99.1
Release     : 0.3.11.rc11.ebf3602git.cmsos14.centos7.gcc4_8_5
Size        : 1.7 M
Repo        : installed
From repo   : gemos-test
Summary     : Base classes for GEM DAQ applications
URL         : https://cms-gem-daq-project.github.io/cmsgemos/
License     : MIT
Description : 

Name        : cmsgemos-gemhardware
Arch        : x86_64
Version     : 0.99.1
Release     : 0.3.11.rc11.ebf3602git.cmsos14.centos7.gcc4_8_5
Size        : 4.5 M
Repo        : installed
From repo   : gemos-test
Summary     : HW interfaces for GEM devices
URL         : https://cms-gem-daq-project.github.io/cmsgemos/
License     : MIT
Description : 

Name        : cmsgemos-gemreadout
Arch        : x86_64
Version     : 0.99.1
Release     : 0.3.11.rc11.ebf3602git.cmsos14.centos7.gcc4_8_5
Size        : 196 k
Repo        : installed
From repo   : gemos-test
Summary     : GEM readout
URL         : https://cms-gem-daq-project.github.io/cmsgemos/
License     : MIT
Description : 

Name        : cmsgemos-gemsupervisor
Arch        : x86_64
Version     : 0.99.1
Release     : 0.3.11.rc11.ebf3602git.cmsos14.centos7.gcc4_8_5
Size        : 1.4 M
Repo        : installed
From repo   : gemos-test
Summary     : GEM Supervisor
URL         : https://cms-gem-daq-project.github.io/cmsgemos/
License     : MIT
Description : 

Name        : cmsgemos-gemutils
Arch        : x86_64
Version     : 0.99.1
Release     : 0.3.11.rc11.ebf3602git.cmsos14.centos7.gcc4_8_5
Size        : 235 k
Repo        : installed
From repo   : gemos-test
Summary     : Utilities for GEM online software
URL         : https://cms-gem-daq-project.github.io/cmsgemos/
License     : MIT
Description : 

Name        : cmsgemos_gempython
Arch        : x86_64
Version     : 0.3.7
Release     : 1.0.21.dev.27a86f1git.cc7.python2.7
Size        : 301 k
Repo        : installed
Summary     : None
URL         : https://cms-gem-daq-project.github.io/gem-plotting-tools
License     : MIT
Description : UNKNOWN
```

**Comment by bdorney** [comment]
Obviously since nothing is performing actions on VFATs if I press `Halt` or `Stop` the VFATs stay in run mode, e.g.:

`GEM_AMC.OH.OH0.GEB.VFAT0.CFG_RUN`

Should go to `0x0` after stopping data taking.

**Comment by jsturdy** [comment]
The fundamental question this discussion should flesh out is: in a given state (transition), what does each piece of hardware **need** to do, and in what order with respect to other hardware.
Are there any new features in the V3 CTP7 FW/OptoHybrid FW/VFAT3 configuration, that need to be done in a specific order, or during a specific transition.

#### Transition summary:
* `Initialize` is where we check that DB connections are available (if requested), HW is reachable
* `Configure` is the transition where we will set all parameters to be ready to take data for a specified run type
* `Start` should do very little, mainly just make sure triggers are ready to flow, links are ready to send data, if decided (see below) VFATs go into `RunMode`
* `Pause`/`Resume`, in local running, stops triggers on the AMC13, but probably doesn't do anything else, in global, may not need to do anything, as TCDS will be `paused`/`resumed` upstream.  Fundamental question is, does something **need** to happen to our hardware in this state
* `Stop` brings the FSM back to the `Configured` state (should only undo `Start` actions)
* `Halt` brings the FSM back to the `Initialized` state (should at most undo up through `Configure` actions)

**Comment by jsturdy** [comment]
> Go to xdaq terminal and when prompted provide CTP7 texas password for dummy phase align script execution,

To avoid this (though perhaps it is useful at present to have this delay), you can add the `ssh` key of the account doing this action to the CTP7's `authorized_keys` file (this is what is done at P5)

**Comment by jsturdy** [comment]
> Should go to 0x0 after stopping data taking.

What are the implications if this does *not* happen?  I.e., if this happens during `Configure` (by calling the CTP7 module that triggers the BLASTER mechanism, which needs to ensure VFATs are in `RunMode` after every `HardReset`) is there any downside

**Comment by cgalloni** [comment]
Definition and cleaning of the FSM transition is planned for the new [architecture.](https://gitlab.cern.ch/cmsgemonline/cmsgemos/-/issues/52)
