### ISSUE TITLE
Feature Request: V3 Hardware Monitoring

### ISSUE THREAD

**Issue by bdorney** [cms-gem-daq-project/cmsgemos#218]
## Brief summary of issue

Requested hardware monitoring in v3 hardware.

For the stuff below I know we have one main monitoring page, but I image that this is *too* much information for that page and so I would suggest it goes in a dedicated sub tab.  E.g. we have the main monitoring page, each AMC has it's own tab (as it is now), and then on each AMC tab there is a sub tab for OH and VFAT monitoring.

### Types of issue

- [ ] Bug report (report an issue with the code)
- [X] Feature request (request for change which adds functionality)

## AMC Monitoring
The MMCM registers are not in the v3 CTP7 FW and will generate bus errors (attribute errors?) if you try to read them.

Also I didn't see the SCA registers in @mexanick's [original PR](https://github.com/cms-gem-daq-project/cmsgemos/pull/205), would suggest to monitor:

- `SCA.READY`, and
- `SCA.CRITICAL_ERROR`

Additionally for each OH we should monitor:

- `GEM_AMC.OH_LINKS.OHX.GBTY_READY`,
- `GEM_AMC.OH_LINKS.OHX.GBTY_WAS_NOT_READY`

In the above two cases `X = {0,..,11}` and `Y = {0,1,2}`; additionally for these two cases suggest a dedicated function in [daq_monitor.h](https://github.com/cms-gem-daq-project/ctp7_modules/blob/develop/include/daq_monitor.h) of `ctp7_modules`.

## Optohybrid Monitoring

We should monitor the registers monitored returned by:

- [getmonTRIGGEROHmainLocal](https://github.com/cms-gem-daq-project/ctp7_modules/blob/ab9f57487ab79e3f37710da4db84835d80b1401f/src/daq_monitor.cpp#L83),
- Firmware release returned by [getmonOHmainLocal](https://github.com/cms-gem-daq-project/ctp7_modules/blob/ab9f57487ab79e3f37710da4db84835d80b1401f/src/daq_monitor.cpp#L264),
- [getmonOHSCAmainLocal](https://github.com/cms-gem-daq-project/ctp7_modules/blob/ab9f57487ab79e3f37710da4db84835d80b1401f/src/daq_monitor.cpp#L368), and
- [getmonOHSysmonLocal](https://github.com/cms-gem-daq-project/ctp7_modules/blob/ab9f57487ab79e3f37710da4db84835d80b1401f/src/daq_monitor.cpp#L523),

@mexanick might already have this (and other monitoring common between v2 and v3 OH's) implemented.

## VFAT Monitoring

For each `OH` we should monitor:

- Sync errors: `GEM_AMC.OH_LINKS.OHX.VFATY.SYNC_ERR_CNT`,
- Errors in DAQ events: `GEM_AMC.OH_LINKS.OHX.VFATY.DAQ_CRC_ERROR_CNT`,
- Temeprature monitoring (see below), and
- Run mode (given experience with VFAT2..???): `GEM_AMC.OH.OHX.GEB.VFATY.CFG_RUN`

For `X = {0,..,11}` and `Y = {0,..,23}`.  Again might want to do this with a dedicated function in [daq_monitor.h](https://github.com/cms-gem-daq-project/ctp7_modules/blob/develop/include/daq_monitor.h) of `ctp7_modules`.

I think only the `SYNC_ERR_CNT` counters here needs to be on the "main" page as a dedicated table.  The rest can go in the sub tab.

### VFAT Temperature Monitoring

We should monitor VFAT temperatures readout by the internal ADC.  This should again be implemented in a dedicated function in [daq_monitor.h](https://github.com/cms-gem-daq-project/ctp7_modules/blob/develop/include/daq_monitor.h) of `ctp7_modules`.

This function would return for each OH two sets of values (24 in total):

- Temperature measured by the internal temperature sensor, and
- Temperature measured by the external temperature sensor

Additionally these two temperature sensors can be readout by either the internally referenced ADC or the externally referenced ADC (for a total of 48 possible values).  I'm not sure which is more stable/reliable at present and overtime the readings will "age" due to radiation exposure of the ADC.  

Finally the ADC will return a voltage value, so we will need a DB query to return ADCX_M and ADCX_B (for `X = 0, 1` 0 is the internally referenced ADC) this will let us convert ADC to voltage.  Figure 31 of the [VFAT3 Manual](https://espace.cern.ch/cms-project-GEMElectronics/VFAT3/VFAT3%20User%20Manual%20v2.2.pdf) shows how voltage converts to temperature:

```
T = 3.7825 * mV + 514.46
```

I would suggest as a starting point to simply display for each OH the 24 temperature values measured by the internal temperature sensor readout by the internally referenced ADC.  For sure this should go on the "sub tab".

This ideally would be useful to have for QC8 since we would need to xcheck that the cooling is "good".

**Comment by lpetre-ulb** [comment]
@dteague, you may be interested how the monitoring variables are split divided into blocks. This eases both the understanding, review and display (in the Web GUI) of the monitorables.

**Comment by dteague** [comment]
[conversation moved here](https://gitlab.cern.ch/cmsgemonline/cmsgemos/-/issues/12). (link fixed)

This issue can be closed

**Comment by cgalloni** [comment]
@dteague  I believe the previous link it's incorrect and you might want to fix it. Anyway, I'll close the PR.
