### ISSUE TITLE
[Bug report]No loop execution in the CTP7 due to wrong NOH being passed 

### ISSUE THREAD

**Issue by mgruchala** [cms-gem-daq-project/cmsgemos#219]
The DACScan root files are empty after executing the scan, due to wrong value being passed to the function.

The problem is not explicite seen as the ```run_scans.py dacScanV3 eagle64 0x4 YY``` is being executed w/o stating any errors, the further look into the log files, shall be taken into consideration. Example below:
```
[gemuser@gem904daq01 2018.11.14.14.32]$ more scanLog.log 
Open pickled address table if available  /opt/cmsgemos/etc/maps//amc_address_table_top.pickle...
Initializing AMC eagle64
opened connection
Getting CHIP IDs of all VFATs
Performing DAC Scan on all links, this may take some time please be patient
Assertion Failed on line 155: rsp.get_word_array_size("dacScanResultsAll") == size
Traceback (most recent call last):
  File "/opt/cmsgemos/bin/dacScanV3.py", line 305, in <module>
    scanAllLinks(args, calTree, vfatBoard)
  File "/opt/cmsgemos/bin/dacScanV3.py", line 95, in scanAllLinks
    raise Exception('RPC response was non-zero, this inidcates an RPC exception occurred')
Exception: RPC response was non-zero, this inidcates an RPC exception occurred
```
### Types of issue

- [x] Bug report (report an issue with the code)
- [ ] Feature request (request for change which adds functionality)

## Expected Behavior

Complementary to what is being stated in the __Current Behaviour__ section.

## Current Behavior

In the file  [amc_user_functions_xhal.py lines 314-317](https://github.com/cms-gem-daq-project/cmsgemos/blob/2d9f965b257b751eb17b20215b8196ec486f327a/gempython/tools/amc_user_functions_xhal.py#L314-L317).The ```NOH```  is being passed as 1 but the unmasked OH is bit 2, so the loop in the CTP7 modules never executes.

### Steps to Reproduce (for bugs)

* On the ```eagle64```, using ```link 2``` execute: ```run_scans.py dacScanV3 eagle64 0x4 YY```, where YY is the DACScan type you wish to perform

## Your Environment

* Version used: [2d9f965](https://github.com/cms-gem-daq-project/cmsgemos/tree/generic-amc-RPC-v3-short-term)
* Shell used: /bin/bash

**Comment by bdorney** [comment]
In the short term take a DAC scan using `dacScanV3.py` instead of `run_scans.py` and use the `--series` option.

I think the longterm fix would just be to change line:

https://github.com/cms-gem-daq-project/cmsgemos/blob/2d9f965b257b751eb17b20215b8196ec486f327a/gempython/tools/amc_user_functions_xhal.py#L325

To:

```python
        return self.dacScanMulti(ohMask, self.nOHs, dacSelect, dacStep, useExtRefADC, dacDataAll)
```

**Comment by lpetre-ulb** [comment]
Fixed in https://github.com/cms-gem-daq-project/cmsgemos/pull/220.
