### ISSUE TITLE
git dirty after typing make

### ISSUE THREAD

**Issue by lmoureaux** [cms-gem-daq-project/cmsgemos#221]
## Brief summary of issue

Just typing
```
make
```
makes the VCS dirty.

### Types of issue

- [x] Bug report (report an issue with the code)
- [ ] Feature request (request for change which adds functionality)

## Expected Behavior

Building software doesn't modify files under version control.

## Current Behavior

On branch `develop`, the file `gemhardware/Makefile.progress` (in git) is modified during the build process.

### Steps to Reproduce (for bugs)

1. Clean build: `BUILD_HOME=$(readlink -f ..) make clean`
2. Reset all files to `HEAD`: `git checkout -- .`
3. Check VCS: `git status` -> clean
4. Build: `BUILD_HOME=$(readlink -f ..) make`
5. Check VCS: `git status`
```
On branch develop
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   gemhardware/Makefile.progress

no changes added to commit (use "git add" and/or "git commit -a")
```

## Possible Solution (for bugs)

If `gemhardware/Makefile.progress` shouldn't be in git, remove it and add it to the list of ignored files. If it should be in git, add a big bold warning to `CONTRIBUTING.md`, document why a tracked file needs to be modified and try to find a cleaner design.

## Context

Setting up a development environment on `gem904daq02`.

## Your Environment

* Version used: `develop` as of today (commit `21ddac5`)
* Shell used: `bash`

**Comment by lpetre-ulb** [comment]
Fixed in #311.
