### ISSUE TITLE
python package structuring

### ISSUE THREAD

**Issue by jsturdy** [cms-gem-daq-project/cmsgemos#223]
Adding the `c++` `boost`ed `python` bindings to the `cmsgemos_gempython` package may bring another restructuring of the `gempython` `python` namespace, in order to keep the `import`s clean.
Currently we have a structure like:
```bash
gempython
├── core
├── gemplotting
│   ├── fitting
│   ├── macros
│   ├── mapping
│   └── utils
├── scripts
├── tools
│   └── xdaq
├── utils
│   └── db
│       └── ldqm_db
└── vfatqc
```

where `gemplotting` and `vfatqc` come from separate repositories, and `core`, `tools`, `utils` come from `cmsgemos_gempython`.
`core` is going to contain the library that `import`s the `boost`ed bindings, i.e., the `cmsgemos` stuff, and being able to do, e.g.,
```python
import gempython.core as cmsgemos

dev = cmsgemos.HwDevice(args)
```
seems to be a reasonable way to scope things.  The question would then be, should all the subpackages currently part of the `cmsgemos_gempython` repository migrate to `core` to be `import`ed with the aforementioned call?

We could then have top level `__init__.py`s in both `gemplotting` and `vfatqc` that would handle such cases as 
```python
import gempython.gemplotting as gp
import gempython.vfatqc as vfatqc
```
by defining what constitutes the package (if necessary)

This structure would then look like:
```bash
gempython
├── core
│   ├── tools
│   │   └── xdaq
│   ├── utils
│   │   └── db
│   │       └── ldqm_db
├── gemplotting
│   ├── fitting
│   ├── macros
│   ├── mapping
│   └── utils
├── scripts
└── vfatqc
```

Since `vfatqc` needs to be updated/redesigned following the `boost`ing, any changes related to the structure of the package can be incorporated at that time

**Comment by mexanick** [comment]
Obsolete
