### ISSUE TITLE
[feature] Populate configuration objects from TStore result

### ISSUE THREAD

**Issue by jsturdy** [cms-gem-daq-project/cmsgemos#235]
## Brief summary of issue
The `TStore` library returns a table result of the DB query, and we need to fill the configuration objects from #231 with the resulting information

### Types of issue
- [x] Feature request (request for change which adds functionality)

**Comment by lpetre-ulb** [comment]
It is unlikely that an Oracle SQL database is going to be used (and by extension the `TStore` library). Discussion about the database system to be used is in [progress on GitLab](https://gitlab.cern.ch/cmsgemonline/cmsgemos/-/issues/68). New issues will be opened with the outcome of this discussion.
