### ISSUE TITLE
[feature] Template Web UI for GEM configuration objects

### ISSUE THREAD

**Issue by jsturdy** [cms-gem-daq-project/cmsgemos#236]
## Brief summary of issue
Provide a simple starting point for a web UI for visualizing the imported configuration object structure, either from a DB view, or from an XML file

### Types of issue
- [x] Feature request (request for change which adds functionality)

## Context
Need to be able to modify certain settings in a user friendly way, or simply just to do a comparison between configuration setting and HW settings.

**Comment by cgalloni** [comment]
Implementation moved to GitLab
