### ISSUE TITLE
[feature][gemonlinedb] Build and run tests on CI

### ISSUE THREAD

**Issue by lmoureaux** [cms-gem-daq-project/cmsgemos#241]
## Brief summary of issue

`gemonlinedb` comes with a set of tests. It's a pity that CI doesn't use them.

### Types of issue

- [ ] Bug report (report an issue with the code)
- [x] Feature request (request for change which adds functionality)

## Expected Behavior

Tests are run on CI, and merging of PR that break tests is blocked.

## Current Behavior

Tests aren't run on CI.

## Possible Solution (for bugs)

Add CI stages that build and run tests. Note that some of them may open a connection to the DB, I'm not sure this can be done on Travis.

## Context

Merging of PR #239 that resulted in issue #240 could have been prevented by CI.

**Comment by jsturdy** [comment]
> Note that some of them may open a connection to the DB, I'm not sure this can be done on Travis.

Unlikely, but will probably be possible in the `gitlab-ci` builds.
Can you separate the tests that require a DB connection, from those that test other features?

May require a new top-level `tests` target and associated rules

**Comment by jsturdy** [comment]
Minimally changed (just to allow compilation) done in #242

**Comment by cgalloni** [comment]
@lmoureaux , can this be closed/or ported to gitlab?

**Comment by lpetre-ulb** [comment]
The tests run and must pass in the new repository CI.
