### ISSUE TITLE
GEM onlinedb fails to compile 

### ISSUE THREAD

**Issue by cgalloni** [cms-gem-daq-project/cmsgemos#251]
## Brief summary of issue

GEM onlinedb package of the branch `feature/gemcalib`  fails to compile with error:
```bash
/afs/cern.ch/work/c/cgalloni/cms-gem-daq-proj/cmsgemos/gemonlinedb/include/gem/onlinedb/AMCConfiguration.h:9:40: fatal error: detail/AMCConfigurationGen.h: No such file or directory
 #include "detail/AMCConfigurationGen.h"
```

### Types of issue

- [x] Bug report (report an issue with the code)
- [ ] Feature request (request for change which adds functionality)

## Expected Behavior

Compile with no errors
### Steps to Reproduce (for bugs)

* Setup your building env
* Run compilation:
```bash
cd $BUILD_HOME/cmsgemos
make clean && make all -j 8
```

## Possible Solution (for bugs)

The following include directive misses the subproject namespace:
```cpp
#include "detail/AMCConfigurationGen.h"
```
Suggestion: prefix such includes with `gem/onlinedb` at all occurences or add the corresponding line to the `Makefile` includes.

## Your Environment

* Version used: branch `cmsgemos/feature-gemcalib`
* Shell used: bash

**Comment by lmoureaux** [comment]
The build succeeds for me. This error is reported because generated headers (`*Gen.h`) are created after the compiler is run to check for header dependencies (creating `.d` files), but it's not fatal and compilation continues.

I'll add the prefix later but errors will still be printed because the underlying problem really lies in the `Makefile`. I don't know how to fix it...

**Comment by jsturdy** [comment]
For me this error is never present when compiling, only when cleaning (e.g., when the command is executed through `/bin/sh -ec 'cmd'`).
Actually, it looks like it's erroring when it tries to generate the `.d` dependency files (though in my case, the headers are qualified as they should be)...
```
/bin/sh -ec 'g++  -MM -g -O2 -Wall -fPIC -fno-omit-frame-pointer -DGIT_VERSION=\"v1.1.0-rc-33-gaa78f4a\" -DGEMDEVELOPER=\"sturdy\" -std=c++1y -std=gnu++1y -O0 -g3 -fno-inline -I/usr/include/python2.7   -I/usr/include/python2.7   -DOS_VERSION_CODE=199168 -Dx86_64_centos7 -Dlinux -DLITTLE_ENDIAN__ -I/opt/xdaq/config -I/tmp/sturdy/cmsgemos/gemonlinedb/include/linux -I/tmp/sturdy/cmsgemos/gemonlinedb/include -I/opt/xdaq/include -I/tmp/sturdy/cmsgemos/gemonlinedb/include -I/tmp/sturdy/cmsgemos/gembase/include -I/tmp/sturdy/cmsgemos/gemutils/include -I/tmp/sturdy/x86_64_centos7/include -I/tmp/sturdy/x86_64_centos7/include/linux -I/opt/xdaq/include -I/opt/xdaq/include/linux  /tmp/sturdy/cmsgemos/gemonlinedb/src/common/VFAT3ChipConfigurationGen.cc > /tmp/sturdy/cmsgemos/gemonlinedb/src/linux/x86_64_centos7/VFAT3ChipConfigurationGen.d' 
/tmp/sturdy/cmsgemos/gemonlinedb/src/common/VFAT3ChipConfigurationGen.cc:7:59: fatal error: gem/onlinedb/detail/VFAT3ChipConfigurationGen.h: No such file or directory
 #include "gem/onlinedb/detail/VFAT3ChipConfigurationGen.h"
```

**Comment by jsturdy** [comment]
OK, in a brand new build setup I replicate the non-fully qualified paths for certain files, as @cgalloni, though, again, the build completes, as these errors only happen during the dependency generation

**Comment by mexanick** [comment]
Indeed, the build completes, but I think we should try to fix this in the future.

**Comment by jsturdy** [comment]
What probably needs to happen is that the code generation should to happen before the `PackageListLoop` is run (or the `ReversePackageListLoop` for a `clean` target), which is a prerequisite of the dependency generation.
I'll take a look at this in the future, but as it's non-blocking now, I don't think it needs attention now

**Comment by lpetre-ulb** [comment]
`gemonlinedb` compiles well in the new repository with the new build system.
