### ISSUE TITLE
VFAT Mask configuration

### ISSUE THREAD

**Issue by mexanick** [cms-gem-daq-project/cmsgemos#27]
setVFATMask is not called by anyone except TBUtils. There should be a parameter in the main XML config and corresponding setter call

**Comment by jsturdy** [comment]
What is the bug?  Currently the code checks which VFATs are connected and uses this to set parameters

**Comment by mexanick** [comment]
The code doesn't mask unavailable VFATs which cause random noise and eventually leads to DAQ electronics overflowing trip.

**Comment by jsturdy** [comment]
VFAT tracking mask is already being set, see [this line](https://github.com/cms-gem-daq-project/cmsgemos/blob/release-v2/gemhardware/src/common/optohybrid/OptoHybridManager.cc#L330), can you confirm that disconnected VFATs are not being masked off?

**Comment by jsturdy** [comment]
Closing, as testing indicates this is not happening in the latest branch.
Reopen if you find this happening.
