### ISSUE TITLE
Packaging variables

### ISSUE THREAD

**Issue by mexanick** [cms-gem-daq-project/cmsgemos#271]
There's a var `INSTALL_PREFIX` mentioned at few occasions, e.g.
https://github.com/cms-gem-daq-project/cmsgemos/blob/447c69671be6c87d06401f7bc53a3c9255d29d0d/config/mfPythonRPM.mk#L173
But it looks like it is not set anywhere and instead `INSTALL_PATH` is used in other places which is correctly defined in corresponding definition files.

**Comment by lpetre-ulb** [comment]
What is the reason to prefer a custom `INSTALL_PREFIX` variable over the `PREFIX` and `DESTDIR` variables? The latter are well-know in `make`, `libtool`, `cmake` and probably all other build systems.

**Comment by jsturdy** [comment]
i picked it up to have a single set of instructions across repositories (since `xdaq` people used it in their makefiles...)

**Comment by lpetre-ulb** [comment]
Okay, that makes sense. This is bad design upstream though, `PREFIX` and `DESTDIR` are two different concepts with different purposes.

**Comment by jsturdy** [comment]
In any event, is this issue still relevant?
As far as I know, everything builds correctly

**Comment by lpetre-ulb** [comment]
I will close the issue as soon as I will have checked that all files are installed to the correct location after a completely clean build.

**Comment by lpetre-ulb** [comment]
RPM packages for the development software won't be produced in this repository.
