### ISSUE TITLE
[feature request] python bindings

### ISSUE THREAD

**Issue by jsturdy** [cms-gem-daq-project/cmsgemos#289]
## Brief summary of issue
Update `python` bindings to the new (after #288 ) codebase
* As a bare minimum (milestone `1.2.X`)
  * All of the current code in `gempython` must be updated to use the exported functions
  * Any mandatory functions which are currently not exported must be
  * Any unnecessary (but currently exported functions) should be removed

### Types of issue
- [x] Feature request (request for change which adds functionality)

## Expected Behavior (target milestone `V2.0.Z`)
It would be fantastic if the bindings could be generated rather than created manually (as we're trying very hard to move away from defining something in 100 different places).
Ideally, this would be done by marking the function for export in the `c++` header file, and then having the binding generator create all bindings.
Something like `libclang`+`cindex` seems like it might be good, but I have only very roughly glanced at it

## Current Behavior
* Bindings are made with `boost::python` 
  * all exported functions must be added to the library (+1 declaration)
  * any functions that have default arguments need a special wrapper (+1 declaration)

## Dependencies
* #288

**Comment by lmoureaux** [comment]
Probably worth looking at the [Python wiki](https://wiki.python.org/moin/IntegratingPythonWithOtherLanguages#C.2FC.2B-.2B-_Binding_Generators)

**Comment by mexanick** [comment]
Obsolete in terms of legacy. Suggest to close here and potentially reopen on giltab in the future.
