### ISSUE TITLE
[feature request] parallelize operations on distinct connections

### ISSUE THREAD

**Issue by jsturdy** [cms-gem-daq-project/cmsgemos#290]
## Brief summary of issue
Current loops that operate on hardware during state transitions loop over all hardware devices.
This should be adapted to parallelize operations done through a single back-end card (`AMC`), and only perform loops where paralleilzation is not actually possible/beneficial (e.g., `OptoHybrid`/`VFAT`)

### Types of issue
- [x] Feature request (request for change which adds functionality)

## Expected Behavior
Perform per`AMC` object actions in parallel

## Current Behavior
Loop is made over `AMC` objects, actions are performed sequentially

**Comment by cgalloni** [comment]
Moved to GitLab [issue](https://gitlab.cern.ch/cmsgemonline/cmsgemos/-/issues/90).
