### ISSUE TITLE
Feature Request: Drop Bits [31:16] of ChipID if rawID is False

### ISSUE THREAD

**Issue by bdorney** [cms-gem-daq-project/cmsgemos#297]
## Brief summary of issue

For older hybrids where `HW_CHIP_ID` is not encoded with Reed-Muller algorithm we can have bit flips in `HW_CHIP_ID` which causes problems when reading/storing this information.  Additionally we know the first set of VFATs have `HW_CHIP_ID` in the range [0,6099].  So a single bit flip in bits `[31:16]` will cause `HW_CHIP_ID` to be wrong.

Here I would propose we only use bits `[15:0]` of `HW_CHIP_ID` when `rawID == False`.  This will partially resolve our bit flip issues in older hybrids and leave current behavior for Reed-Muller encoded chips unchanged.  

### Types of issue

- [ ] Bug report (report an issue with the code)
- [x] Feature request (request for change which adds functionality)

## Expected Behavior

If `rawID == False` I would propose to drop higher bits of the chipID:

```python
for vfat in len(chipIDData):
   chipIDData[vfat] = chipIDData[vfat] & 0xffff
```

## Current Behavior

https://github.com/cms-gem-daq-project/cmsgemos/blob/d05a2efcb444d43ad703d8527e6161d7646dba83/gempython/tools/vfat_user_functions_xhal.py#L121-L135

## Context

See discussion above.

## Your Environment

* Version used: d05a2efcb444d43ad703d8527e6161d7646dba83
* Shell used:

**Comment by jsturdy** [comment]
> So a single bit flip in bits [31:16] will cause HW_CHIP_ID to be wrong.

And in the case where the bit flip happens in bits `[15:0]`... we accept that a subsequent action done based on the ID may very well be incorrect?
I don't think I would blindly mask off these bits, but would rather print an error/warning to the output, so that a person could be alerted if there is a potential for such an outcome.

**Comment by bdorney** [comment]
> And in the case where the bit flip happens in bits [15:0]... we accept that a subsequent action done based on the ID may very well be incorrect?

Yes right now that's the only option I think; right now a DB query on this info will print a warning if a VFAT chipID is not found in the DB:

https://github.com/cms-gem-daq-project/gem-plotting-tools/blob/a51324ac284f894979aa5f53260411437dcf6068/utils/dbutils.py#L77-L79

> I don't think I would blindly mask off these bits, but would rather print an error/warning to the output, so that a person could be alerted if there is a potential for such an outcome.

We can of course implement an error/warning; but these higher bits have routinely caused problems later on when attempting to store/retrieve this data in `vfatqc` and `gem-plotting-tools` due to array size; I've tried many different ways to get an unsigned 32 bit integer accepted in the `array` class:

https://docs.python.org/2/library/array.html

But event when using `L` here:

https://github.com/cms-gem-daq-project/gem-plotting-tools/blob/a51324ac284f894979aa5f53260411437dcf6068/utils/scurveAlgos.py#L495-L496

https://github.com/cms-gem-daq-project/vfatqc-python-scripts/blob/dae6fb9a1d65f0d7081dc040832faf1c5f77123e/utils/treeStructure.py#L41-L42

The QC7/8 teams have reported that readbacks of HW_CHIP_ID from non-reed muller encoded hybrids cause overflow errors either at time of acquisition or later analysis.

I'm not sure how to solve this.

**Comment by bdorney** [comment]
The issue should be moved to gem-plotting-tools.

**Comment by jsturdy** [comment]
By any chance, does [this](https://github.com/pandas-dev/pandas/issues/15453) seem like the true culprit?
