### ISSUE TITLE
[Discussion/feature request] Remove SSH calls to the CTP7

### ISSUE THREAD

**Issue by lpetre-ulb** [cms-gem-daq-project/cmsgemos#305]
## Brief summary of issue

Currently some actions are triggered on the CTP7 through SSH. This solution is not portable between boards in some (all?) cases.

For example, the PROMless activation before OH FPGA programming is checked as follow: 
https://github.com/cms-gem-daq-project/cmsgemos/blob/444c322e99e0a7b522bc27e8818a0731df4cfff5/gempython/tools/amc_user_functions_xhal.py#L773-L780

And this doesn't work for the GLIB emulator for which the PROMless configuration procedure is different.

(The issue is opened is `cmsgemos`, but SSH calls can very well be made in other repositories.)

### Types of issue

- [ ] Bug report (report an issue with the code)
- [x] Feature request (request for change which adds functionality)

## Context

Porting the `GEM_AMC` firmware to the GLIB and trying to run `testConnectivity.py`.

## Proposal

I think each SSH call has its own solution:

* Modifying the VFAT3 settings in text files on the CTP7 will be automatically fixed with the config blaster and the new GEM online software.
* The PROMless can either be configured and enabled in the backend recovery procedure or can be ported to a RPC module whose implementation is specific to the backend. I'm not sure what the best operational solution is, but both should work on all boards.

## Your Environment

* Version used: https://github.com/cms-gem-daq-project/cmsgemos/tree/444c322e99e0a7b522bc27e8818a0731df4cfff5

**Comment by jsturdy** [comment]
Strongly in favour of removing ad hoc `ssh` calls from everywhere, but in this case, I know that it was necessary as the underlying register wasn't exposed in the FW

**Comment by mexanick** [comment]
is this still relevant?

**Comment by lpetre-ulb** [comment]
Probably not, the legacy release won't be updated and it shouldn't apply to the new SW architecture.
