### ISSUE TITLE
HwGenericAMC::getSupportedOptoHybrids not working

### ISSUE THREAD

**Issue by lpetre-ulb** [cms-gem-daq-project/cmsgemos#317]
## Brief summary of issue

According to a comment PR #315, the `HwGenericAMC::getSupportedOptoHybrids` does not seem to work: https://github.com/cms-gem-daq-project/cmsgemos/pull/315/files#r385062437

### Types of issue

- [x] Bug report (report an issue with the code)
- [ ] Feature request (request for change which adds functionality)

## Expected Behavior

The function should return the number of OptoHybrids supported by the AMC firmware.

## Current Behavior

:question: @mexanick, you probably have more information?

## Your Environment

* Version used: https://github.com/cms-gem-daq-project/cmsgemos/commit/f20b7fb64d90cd24bc75be5716c6c43d76cc3892

**Comment by jsturdy** [comment]
The function is really stupidly simple, so why it wouldn't work is strange... (unless the register name is no longer as stated)

https://github.com/cms-gem-daq-project/cmsgemos/blob/f20b7fb64d90cd24bc75be5716c6c43d76cc3892/gemhardware/devices/src/common/amc/HwGenericAMC.cc#L205-L208

**Comment by mexanick** [comment]
I have no idea... It actually might be a different thing, not exactly this function. The loop was commented out because it was leading to endless loop and because it is actually not needed anywhere. I didn't get why it was endless though...
