### ISSUE TITLE
Unified Boost version selection

### ISSUE THREAD

**Issue by lmoureaux** [cms-gem-daq-project/cmsgemos#320]
## Brief summary of issue

I would like to use Boost.Beast for `gemonlinedb` uploads to the DB loader (I settled on HTTP uploads because they are synchronous and C++ libraries for HTTP are easier to use). This library is only present in Boost 1.69 (first added in 1.66).

Currently three versions of Boost are installed on `gemdaq-build-xdaq15`:

* `boost-devel-1.53.0-27.el7.x86_64` in `/usr/include/` and `/usr/lib64/`
* `boost148-devel-1.48.0-7.el7.x86_64` in `/usr/include/boost148/` and `/usr/lib64/boost148/`
* `boost169-devel-1.69.0-2.el7.x86_64` in `/usr/include/boost169/` and `/usr/lib64/boost169/`

So fine! Let's use 1.69! Actually it's not that simple: since Boost doesn't guarantee binary (or even source) compatibility between versions, sticking to a single version of it thorough all `cmsgemos` modules is critical, both at build time and at runtime.

### Types of issue

- [ ] Bug report (report an issue with the code)
- [x] Feature request (request for change which adds functionality)

## Expected Behavior

A single version of Boost can be selected easily for the whole build.

## Current Behavior

The system-wide default version of Boost is always used.

## Possible Solution

A `mkBoostDefsGEM.mk` file could be added to `config` (`FindBoost.cmake` I'm looking at you), that would set up the necessary flags to:

* Add the selected version of Boost to `DependentLibraryDirs` and `IncludeDirs`
* Add the correct location to the `RUNPATH` of produced binaries
* Anything else necessary? RPM build-time deps?

Alternatively static linking could work *if no Boost objects are ever used in the public API*.

## Context

Willing to use a newer version of Boost that is already installed on the system.

**Comment by mexanick** [comment]
@lmoureaux any idea of why we have 3 boosts and which ones are used and by which package? I don't recall us using the boost apart from python bindings export (that should be easy to update if anything is required). Maybe the more recent one is brought by devtoolset-8 which we use for modern compilers?

**Comment by lmoureaux** [comment]
> any idea of why we have 3 boosts and which ones are used and by which package?

Good question, I couldn't find a reverse dependency for any of the Boost packages. This may be the result of `yum install boost*`

> I don't recall us using the boost apart from python bindings export (that should be easy to update if anything is required).

Boost is used in various places in `cmsgemos`. I saw `algorithm`, `format`, `regex`, `python`, `filesystem`, `test`, `iostreams` and `unordered_map`. These parts of Boost are probably more or less stable nowadays but I really want Beast :)

**Comment by mexanick** [comment]
Well, I'd say you should start trying to implement boost with Beast locally for the moment (I mean, for gemonlinedb package only), while we will investigate other boosts and if there's no need to keep all three versions, we will just use the most recent one. Considering build system: as you probably heard last dev meeting, we are planning to revise the building system eventually switching to cmake and static linking. Moreover, the repository/ies structure will be updated too, so I would not really bother right now with "production" implementation of the boost version selection until we decide finally on exact revision of the build system.

**Comment by lpetre-ulb** [comment]
Just to be sure, isn't xDAQ linked against a specific version of `boost` (system-wide installation?)? If so, the safest way would be to go for that version. Note that CC8 is going to be released with `boost` 1.66.

**Comment by jsturdy** [comment]
> Just to be sure, isn't xDAQ linked against a specific version of `boost` (system-wide installation?)? If so, the safest way would be to go for that version. Note that CC8 is going to be released with `boost` 1.66.

I was going to ask what implications any change in our codebase would have on how we interact with other libraries, as I know `ipbus` (dependency through AMC13` SW) is built against 1.66 (for both cc7 and cc8)

**Comment by lmoureaux** [comment]
Both `uhal` and `xdaq` export symbols with Boost 1.53 data types. I still have no idea how the other Boost versions came to be installed, maybe with `yum install boost*`?

So we can't use a newer version before switching to CC8/xDAQ 16.
