### ISSUE TITLE
gemonlinedb tests fail with a missing file

### ISSUE THREAD

**Issue by lpetre-ulb** [cms-gem-daq-project/cmsgemos#322]
## Brief summary of issue

One `gemonlinedb` test case fails with the error reported hereunder.

### Types of issue

- [x] Bug report (report an issue with the code)
- [ ] Feature request (request for change which adds functionality)

## Expected Behavior

All tests should pass.

## Current Behavior

`gemonlinedb` tests fail with the following error:

``` bash
$ make run-tests
[...]
Testing: test/testFileConfigurationProvider.exe
Running 6 test cases...
unknown location(0): fatal error in "LoadNonCompliant": std::runtime_error: File not found in path: No such file or directory: "xml/tests/NonCompliantFile.json", "."
test/testFileConfigurationProvider.cc(84): last checkpoint

*** 1 failure detected in test suite "TestFileConfigurationProvider"
[...]
```

Notice that `echo $?` returns `0`, as if no error occurred.

### Steps to Reproduce (for bugs)

1. Fetch the HEAD of `develop`
2. Build the libraries `make`
3. Build and launch the tests `make run-tests`
4. Look at the result

## Possible Solution (for bugs)

Replace the current XML test file with the expected JSON test file.

## Context

Launching tests after some modifications.

## Your Environment

* Version used: branch `develop`/https://github.com/cms-gem-daq-project/cmsgemos/commit/74641ce523d9f973409dd29daf290b69db05bcc5

**Comment by lmoureaux** [comment]
I'm working on a PR. In the meantime the test should pass if you `touch gemonlinedb/xml/tests/NonCompliantFile.json`.

**Comment by lmoureaux** [comment]
Thank you for running the tests and reporting failures! :heart_eyes:
