### ISSUE TITLE
XDAQ Monitoring updating

### ISSUE THREAD

**Issue by dteague** [cms-gem-daq-project/cmsgemos#329]
The XDAQ monitoring code needs to be updated to V3 as well as become more robust. This issue is to discuss changes needed in the newest version of Monitoring code as well as to resolve issues associated with setting that up

## Update to V3
The current daqmonitoring code is older and thus hasn't been updated to V3 changes in the firmware. Old V2 parts need to be removed as well as making sure all of the new values are displayed in the code.

## Generalization of functions
Many of the function calls are very specific and this can be genericised using possibly different mapping for variables, templated classes, etc. A suggestion made by @lpetre-ulb 

>  Still regarding the monitoring, in order to reduce the code duplication, I was thinking about a filter system. The RPC module would populate a dictionary with abstract/symbolic names; they wouldn't necessarily correspond to register names since the latter do not always exist (e.g. the PT1000 sensors). The separator could even be a / instead of a . to stress the difference.
> On the DAQ software side (current cmsgemos), the monitoring variables would go through different filters, defined in data files (JSON or XML), depending on the target. Indeed, only some parameters will have to be forwarded to DCS for instance. The names could also be adapted depending on the requirements, DCS vs display name for the Web GUI.

These changes will have to be thought out to make a sensible code base.

## And More!
The above are first steps and more functions can be talked about in this issue and/or PRs as the code changes become more mature

**Comment by cgalloni** [comment]
implementation moved to gitlab
