### ISSUE TITLE
Correct XML configuration files missing in the repository

### ISSUE THREAD

**Issue by mexanick** [cms-gem-daq-project/cmsgemos#330]
## Brief summary of issue

Current xml configuration files won't work with the updated code. Need to provide the working example or template of the xml config when changes requiring the change of XML are performed
### Types of issue

- [ ] Bug report (report an issue with the code)
- [ ] Feature request (request for change which adds functionality)
- [x] Documentation update 

## Possible Solution 

Since currently `gemsupervisor` is the entry point, the easiest way is to keep valid xml configuration example there. However I'd accept other ideas on hosting the relevant config (e.g. website with documentation) 
## Your Environment

* Version used: latest `develop`
* Shell used:

**Comment by lpetre-ulb** [comment]
[Moved to GitLab.](https://gitlab.cern.ch/cmsgemonline/cmsgemos/issues/17)
