### ISSUE TITLE
Feature Request: Hex 2 Decimal Conversion on Selected Registers

### ISSUE THREAD

**Issue by bdorney** [cms-gem-daq-project/cmsgemos#55]
Would it be possible to change on GLIBManager -> Card Page -> DAQ the following registers:

->EVT_SENT
->L1AID
->RUN_PARAMS

To appear in decimal notation rather than Hex?

**Comment by jsturdy** [comment]
Addressed in #56 
RUN_PARAMS will not be included as it won't make sense (it's a composite 32 bit number with groups of 8 bits meaning different things)
