### ISSUE TITLE
AMC13 manager configuration

### ISSUE THREAD

**Issue by mexanick** [cms-gem-daq-project/cmsgemos#6]
AMC13 Manager crashes when attempting to connect to unavailable amc13 (e.g. wrong amc13 connection file provided)

**Comment by jotadram6** [comment]
Can you please to retry at TIF with /afs/
cern.ch/work/j/jruizalv/public/GEM_DAQ/cmsgemos/setup/etc/addresstables/connections_ch.xml
? You should also take a look at the config file: /afs/
cern.ch/work/j/jruizalv/public/GEM_DAQ/cmsgemos/gemsupervisor/xml/gemsupervisor_tif.xml

On Thu, Jun 30, 2016 at 11:20 AM, Mykhailo Dalchenko <
notifications@github.com> wrote:

> Assigned #6 <https://github.com/cms-gem-daq-project/cmsgemos/issues/6> to
> @jotadram6 <https://github.com/jotadram6>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/cms-gem-daq-project/cmsgemos/issues/6#event-708892021>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AApYfK6CkEfT8_lk5GlJxIXu8aTJgvvyks5qQ4p2gaJpZM4JB9l4>
> .
>



-- 
_______________________________
José David Ruiz Álvarez
CMS Group - Universidad de los Andes
CERN - Office: 42 - R - 036
_______________________________

**Comment by mexanick** [comment]
Dear Jose,
I know that the code works when valid configuration is provided. But in my opinion it shouldn't crash when configuration points to unexisting amc13 board (i.e. when you run setup at TIF with config from 904). It should instead report smth like "board unavailable" and go to error state, but not crash.

**Comment by jotadram6** [comment]
Ok, I see now your point. I agree with you, I'll work on the code to
implement what you are asking for.

On Thu, Jun 30, 2016 at 11:38 AM, Mykhailo Dalchenko <
notifications@github.com> wrote:

> Dear Jose,
> I know that the code works when valid configuration is provided. But in my
> opinion it shouldn't crash when configuration points to unexisting amc13
> board (i.e. when you run setup at TIF with config from 904). It should
> instead report smth like "board unavailable" and go to error state, but not
> crash.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/cms-gem-daq-project/cmsgemos/issues/6#issuecomment-229611280>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AApYfKPMc-p-ZasjGtYov8ZuyVO-iY4Iks5qQ46pgaJpZM4JB9l4>
> .
>



-- 
_______________________________
José David Ruiz Álvarez
CMS Group - Universidad de los Andes
CERN - Office: 42 - R - 036
_______________________________

**Comment by jsturdy** [comment]
Has this been resolved?

**Comment by jsturdy** [comment]
Changing milestone, as this will not hold up v0.2.1

**Comment by jsturdy** [comment]
Stale and/or no longer an issue
