### ISSUE TITLE
Feature Request: EVT_SENT Register Reset on "Start":

### ISSUE THREAD

**Issue by bdorney** [cms-gem-daq-project/cmsgemos#71]
If issuing "Start" the EVT_SENT register on the GLIBManager -> Card Page -> DAQ subtab the counter corresponding to this register does not reset while the L1AID register does.  This could cause potential confusion.

Request that on "Start" this counter is reset along with the L1AID register.  See image attached.
![evt_sent_counter_not_refreshed](https://cloud.githubusercontent.com/assets/6432141/20856320/685a5530-b90c-11e6-9c4c-d6e4299ff9a9.png)

**Comment by jsturdy** [comment]
I believe that this is a firmware bug and the generic AMC firmware has this behaviour implemented correctly, though I'll have to check with @evka85

**Comment by jsturdy** [comment]
Also to be reset on start:
* VFAT CRC counters
* OH T1 counters
* AMC T1 counters
