### ISSUE TITLE
Bug Report: icomp value ignored

### ISSUE THREAD

**Issue by bdorney** [cms-gem-daq-project/cmsgemos#83]
Noticed that the value passed to icomp in the CommonVFATSettings is not used and instead a value of 90 is applied to all chips.

Steps to repeat the problem:

->launch xdaq
->Initialize
->Configure
->Check VFAT Dashboard using the WebDAQ

You'll see icomp is 90.

**Comment by lpetre-ulb** [comment]
v2 electronics specific
