### ISSUE TITLE
Bug Report: GLIB FIFO Full @ Start

### ISSUE THREAD

**Issue by bdorney** [cms-gem-daq-project/cmsgemos#84]
We performed an ultra-scan with the webDAQ to look at the thresholds before starting a run with xdaq.

We noticed that this fills the GLIB FIFO.

When starting the run with xdaq the FIFO was full and then no further triggers were accepted.

This seems like a rare case but maybe the GLIB FIFO should be "flushed" when pressing "start."

**Comment by jsturdy** [comment]
The GLIB FIFO reported on the web DAQ is unrelated to the blocked triggers.
However, what does cause problems is if the GLIB was receiving triggers before it was in "run mode", which sounds like may have happened somehow.

**Comment by bdorney** [comment]
GLIB no longer used.
